////////////////////////////////////////////////////////////////////////
//
// vmf/vmf1_inputtoresult.cs
//
// This file was generated by MapForce 2011r2.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the MapForce Documentation for further details.
// http://www.altova.com/mapforce
//
////////////////////////////////////////////////////////////////////////

using System.Collections;


// application.libraries
namespace vmf

{
	
	public class vmf1_inputtoresult : Altova.TraceProvider 
	{




	class Main : IEnumerable
	{
		string var1_input;
	
		public Main(
			string var1_input
			)
		{
			this.var1_input = var1_input;
		}

		public IEnumerator GetEnumerator() { return Altova.Mapforce.MFEmptySequence.Instance.GetEnumerator(); }
				
	}


	public static IEnumerable Create(
		string var1_input
		)
	{

		object o = hash[var1_input];
		if (o != null)
			return new Altova.Mapforce.MFSingletonSequence(o);
		else
			return Altova.Mapforce.MFEmptySequence.Instance;

	}

		static Hashtable hash = new Hashtable();
		static vmf1_inputtoresult()
		{
			hash["CY-CY"] = "1";	
			hash["CY-DOOR"] = "2";	
			hash["CY-CFS"] = "3";	
			hash["Cy to C\'haul on cy"] = "4";	
			hash["CY-TACKLE"] = "5";	
			hash["CY-FREE OUT"] = "6";	
			hash["Cy to Mixed"] = "7";	
			hash["DOOR-CY"] = "8";	
			hash["DOOR-DOOR"] = "9";	
			hash["DOOR-CFS"] = "10";	
			hash["Door to C\'haul on cy"] = "11";	
			hash["Door to Tackle"] = "12";	
			hash["DR-FREE OUT"] = "13";	
			hash["Door to Mixed"] = "14";	
			hash["C\'haul on cy to Cy"] = "15";	
			hash["C\'haul on cy to Door"] = "16";	
			hash["C\'haul on cy to CFS"] = "17";	
			hash["C\'haul on cy to C\'haul on cy"] = "18";	
			hash["C\'haul on cy to Tackle"] = "19";	
			hash["C\'haul on cy to Free out"] = "20";	
			hash["C\'haul on cy to Mixed"] = "21";	
			hash["TACKLE-CY"] = "22";	
			hash["Tackle to Door"] = "23";	
			hash["TACKLE-CFS"] = "24";	
			hash["Tackle to C\'haul on cy"] = "25";	
			hash["Tackle to Tackle"] = "26";	
			hash["Tackle to Free out"] = "27";	
			hash["Tackle to Mixed"] = "28";	
			hash["FREE IN-CY"] = "29";	
			hash["FREE IN-DR"] = "30";	
			hash["Free in to CFS"] = "31";	
			hash["Free in to C\'haul on cy"] = "32";	
			hash["Free in to Tackle"] = "33";	
			hash["FREE IN-FREE OUT"] = "34";	
			hash["Free in to Mixed"] = "35";	
			hash["Mixed to Cy"] = "36";	
			hash["Mixed to Door"] = "37";	
			hash["Mixed to CFS"] = "38";	
			hash["Mixed to C\'haul on cy"] = "39";	
			hash["Mixed to Tackle"] = "40";	
			hash["Mixed to Free out"] = "41";	
			hash["Mixed to Mixed"] = "42";	
		}

  } 
}
