////////////////////////////////////////////////////////////////////////
//
// vmf/vmf4_inputtoresult.cs
//
// This file was generated by MapForce 2011r2.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the MapForce Documentation for further details.
// http://www.altova.com/mapforce
//
////////////////////////////////////////////////////////////////////////

using System.Collections;


namespace vmf

{
	
	public class vmf4_inputtoresult : Altova.TraceProvider 
	{




	class Main : IEnumerable
	{
		string var1_input;
	
		public Main(
			string var1_input
			)
		{
			this.var1_input = var1_input;
		}

		public IEnumerator GetEnumerator() { return Altova.Mapforce.MFEmptySequence.Instance.GetEnumerator(); }
				
	}


	public static IEnumerable Create(
		string var1_input
		)
	{

		object o = hash[var1_input];
		if (o != null)
			return new Altova.Mapforce.MFSingletonSequence(o);
		else
			return Altova.Mapforce.MFEmptySequence.Instance;

	}

		static Hashtable hash = new Hashtable();
		static vmf4_inputtoresult()
		{
			hash["1"] = "01";	
			hash["2"] = "02";	
			hash["3"] = "03";	
			hash["4"] = "04";	
			hash["5"] = "05";	
			hash["6"] = "06";	
			hash["7"] = "07";	
			hash["8"] = "08";	
			hash["9"] = "09";	
			hash["10"] = "10";	
			hash["11"] = "11";	
		}

  } 
}
