//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICP.WF.FormDesigner.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_EN() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ICP.WF.FormDesigner.Resources.Resource_EN", typeof(Resource_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 There is already a creator registered for the format 的本地化字符串。
        /// </summary>
        internal static string AlreadyContainCreatorRegisteredFormat {
            get {
                return ResourceManager.GetString("AlreadyContainCreatorRegisteredFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Form is not preserved, whether or not to preserve the paper form? 的本地化字符串。
        /// </summary>
        internal static string AreYouSureSaveForm {
            get {
                return ResourceManager.GetString("AreYouSureSaveForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t create datasource 的本地化字符串。
        /// </summary>
        internal static string CantCreateDatasource {
            get {
                return ResourceManager.GetString("CantCreateDatasource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t open file 的本地化字符串。
        /// </summary>
        internal static string Cantopenfile {
            get {
                return ResourceManager.GetString("Cantopenfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In the code view mode, do not support this feature 的本地化字符串。
        /// </summary>
        internal static string CodeViewModeNotSupportThisFeature {
            get {
                return ResourceManager.GetString("CodeViewModeNotSupportThisFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Source Designer 的本地化字符串。
        /// </summary>
        internal static string DataSourceDesigner {
            get {
                return ResourceManager.GetString("DataSourceDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error occured in reading Toolbox.xml file. 的本地化字符串。
        /// </summary>
        internal static string ErrorOccuredInReadingToolboxConfigFile {
            get {
                return ResourceManager.GetString("ErrorOccuredInReadingToolboxConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Event {0} does not exist on {1} 的本地化字符串。
        /// </summary>
        internal static string EventDoesNotExist {
            get {
                return ResourceManager.GetString("EventDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Event {0} has no method bound to it 的本地化字符串。
        /// </summary>
        internal static string EventHasNotMethodBoundToIt {
            get {
                return ResourceManager.GetString("EventHasNotMethodBoundToIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 failly 的本地化字符串。
        /// </summary>
        internal static string Failly {
            get {
                return ResourceManager.GetString("Failly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Already Exists!!! 的本地化字符串。
        /// </summary>
        internal static string FileIsexists {
            get {
                return ResourceManager.GetString("FileIsexists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Not Existed 的本地化字符串。
        /// </summary>
        internal static string FileNotExisted {
            get {
                return ResourceManager.GetString("FileNotExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Form Designer 的本地化字符串。
        /// </summary>
        internal static string FormDesigner {
            get {
                return ResourceManager.GetString("FormDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Form File 的本地化字符串。
        /// </summary>
        internal static string FormFile {
            get {
                return ResourceManager.GetString("FormFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name cannot contain a space character! 的本地化字符串。
        /// </summary>
        internal static string FormNameCannotContainSpaceCharacter {
            get {
                return ResourceManager.GetString("FormNameCannotContainSpaceCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid designerLoaderHost. 的本地化字符串。
        /// </summary>
        internal static string InvalidDesignerLoaderHost {
            get {
                return ResourceManager.GetString("InvalidDesignerLoaderHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item has no type attribute 的本地化字符串。
        /// </summary>
        internal static string ItemHasNoTypeAttribute {
            get {
                return ResourceManager.GetString("ItemHasNoTypeAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item type {0} could not be found. 的本地化字符串。
        /// </summary>
        internal static string ItemTypeCouldNotBeFound {
            get {
                return ResourceManager.GetString("ItemTypeCouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Node type {0} is not allowed here 的本地化字符串。
        /// </summary>
        internal static string llowedHere {
            get {
                return ResourceManager.GetString("llowedHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Member {0} requires {1} arguments, not {2}. 的本地化字符串。
        /// </summary>
        internal static string MethodRequiresArguments {
            get {
                return ResourceManager.GetString("MethodRequiresArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Must Input 的本地化字符串。
        /// </summary>
        internal static string MustInput {
            get {
                return ResourceManager.GetString("MustInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No event name 的本地化字符串。
        /// </summary>
        internal static string NoEventName {
            get {
                return ResourceManager.GetString("NoEventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Exists Toolbox Config File 的本地化字符串。
        /// </summary>
        internal static string NoExistsConfigFile {
            get {
                return ResourceManager.GetString("NoExistsConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No member attribute 的本地化字符串。
        /// </summary>
        internal static string NoMemberAttribute {
            get {
                return ResourceManager.GetString("NoMemberAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No page design 的本地化字符串。
        /// </summary>
        internal static string NoPageDesign {
            get {
                return ResourceManager.GetString("NoPageDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Does not support the file format 的本地化字符串。
        /// </summary>
        internal static string NotSupportTheFileFormat {
            get {
                return ResourceManager.GetString("NotSupportTheFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;Object&gt; tag is missing required type attribute 的本地化字符串。
        /// </summary>
        internal static string ObjectTagMissingTypeAttribute {
            get {
                return ResourceManager.GetString("ObjectTagMissingTypeAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only Item elements are allowed in collections, not {0} elements. 的本地化字符串。
        /// </summary>
        internal static string OnlyAllowItemElements {
            get {
                return ResourceManager.GetString("OnlyAllowItemElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only Property elements are allowed in collections, not {0} elements. 的本地化字符串。
        /// </summary>
        internal static string OnlyAllowPropertyElements {
            get {
                return ResourceManager.GetString("OnlyAllowPropertyElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Property {0} does not exist on {1} 的本地化字符串。
        /// </summary>
        internal static string PropertyDoesNotExist {
            get {
                return ResourceManager.GetString("PropertyDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Property has no name 的本地化字符串。
        /// </summary>
        internal static string PropertyHasNoName {
            get {
                return ResourceManager.GetString("PropertyHasNoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save changes to existing designer? 的本地化字符串。
        /// </summary>
        internal static string SaveChangeToDesigner {
            get {
                return ResourceManager.GetString("SaveChangeToDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Successfully 的本地化字符串。
        /// </summary>
        internal static string Successfully {
            get {
                return ResourceManager.GetString("Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tip 的本地化字符串。
        /// </summary>
        internal static string Tip {
            get {
                return ResourceManager.GetString("Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type {0} could not be loaded. 的本地化字符串。
        /// </summary>
        internal static string TypeCouldNotBeLoaded {
            get {
                return ResourceManager.GetString("TypeCouldNotBeLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to contact event binding service so we can&apos;t bind any events 的本地化字符串。
        /// </summary>
        internal static string UnableBindAnyEvents {
            get {
                return ResourceManager.GetString("UnableBindAnyEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Undefined Host Type 的本地化字符串。
        /// </summary>
        internal static string UndefinedHostType {
            get {
                return ResourceManager.GetString("UndefinedHostType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unexpected element type {0} 的本地化字符串。
        /// </summary>
        internal static string UnexpectedElementType {
            get {
                return ResourceManager.GetString("UnexpectedElementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unsaved Changes 的本地化字符串。
        /// </summary>
        internal static string UnsavedChanges {
            get {
                return ResourceManager.GetString("UnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wrong file name or the path of the file does not exist 的本地化字符串。
        /// </summary>
        internal static string WrongNameOrFileNotExisted {
            get {
                return ResourceManager.GetString("WrongNameOrFileNotExisted", resourceCulture);
            }
        }
    }
}
