//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICP.WF.FormDesigner.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_CN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_CN() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ICP.WF.FormDesigner.Resources.Resource_CN", typeof(Resource_CN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 已经有一个创建注册的格式 的本地化字符串。
        /// </summary>
        internal static string AlreadyContainCreatorRegisteredFormat {
            get {
                return ResourceManager.GetString("AlreadyContainCreatorRegisteredFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表单未保存，是否保存该表单文件？ 的本地化字符串。
        /// </summary>
        internal static string AreYouSureSaveForm {
            get {
                return ResourceManager.GetString("AreYouSureSaveForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能创建数据源. 的本地化字符串。
        /// </summary>
        internal static string CantCreateDatasource {
            get {
                return ResourceManager.GetString("CantCreateDatasource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能打开文件. 的本地化字符串。
        /// </summary>
        internal static string Cantopenfile {
            get {
                return ResourceManager.GetString("Cantopenfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在代码视图模式下,不支持该功能. 的本地化字符串。
        /// </summary>
        internal static string CodeViewModeNotSupportThisFeature {
            get {
                return ResourceManager.GetString("CodeViewModeNotSupportThisFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据源设计器 的本地化字符串。
        /// </summary>
        internal static string DataSourceDesigner {
            get {
                return ResourceManager.GetString("DataSourceDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 具条配置文件时，发生错误． 的本地化字符串。
        /// </summary>
        internal static string ErrorOccuredInReadingToolboxConfigFile {
            get {
                return ResourceManager.GetString("ErrorOccuredInReadingToolboxConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事件件{0}不存在类型{1}中. 的本地化字符串。
        /// </summary>
        internal static string EventDoesNotExist {
            get {
                return ResourceManager.GetString("EventDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}事件没方法关联它. 的本地化字符串。
        /// </summary>
        internal static string EventHasNotMethodBoundToIt {
            get {
                return ResourceManager.GetString("EventHasNotMethodBoundToIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败. 的本地化字符串。
        /// </summary>
        internal static string Failly {
            get {
                return ResourceManager.GetString("Failly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该文件已经存在，请重新命名 的本地化字符串。
        /// </summary>
        internal static string FileIsexists {
            get {
                return ResourceManager.GetString("FileIsexists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件不存在 的本地化字符串。
        /// </summary>
        internal static string FileNotExisted {
            get {
                return ResourceManager.GetString("FileNotExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表单设计器 的本地化字符串。
        /// </summary>
        internal static string FormDesigner {
            get {
                return ResourceManager.GetString("FormDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表单文件 的本地化字符串。
        /// </summary>
        internal static string FormFile {
            get {
                return ResourceManager.GetString("FormFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称不能包含空格等特殊字符． 的本地化字符串。
        /// </summary>
        internal static string FormNameCannotContainSpaceCharacter {
            get {
                return ResourceManager.GetString("FormNameCannotContainSpaceCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 designerLoaderHost无效。 的本地化字符串。
        /// </summary>
        internal static string InvalidDesignerLoaderHost {
            get {
                return ResourceManager.GetString("InvalidDesignerLoaderHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item不存在[Type]特性. 的本地化字符串。
        /// </summary>
        internal static string ItemHasNoTypeAttribute {
            get {
                return ResourceManager.GetString("ItemHasNoTypeAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item类型{0}无法找到。 的本地化字符串。
        /// </summary>
        internal static string ItemTypeCouldNotBeFound {
            get {
                return ResourceManager.GetString("ItemTypeCouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这里不允许存在节点类型{0}. 的本地化字符串。
        /// </summary>
        internal static string llowedHere {
            get {
                return ResourceManager.GetString("llowedHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 方法{0}需要{1}个参数,而不是{2}个. 的本地化字符串。
        /// </summary>
        internal static string MethodRequiresArguments {
            get {
                return ResourceManager.GetString("MethodRequiresArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须填写 的本地化字符串。
        /// </summary>
        internal static string MustInput {
            get {
                return ResourceManager.GetString("MustInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有事件名称. 的本地化字符串。
        /// </summary>
        internal static string NoEventName {
            get {
                return ResourceManager.GetString("NoEventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 具箱的配置文件不存在！ 的本地化字符串。
        /// </summary>
        internal static string NoExistsConfigFile {
            get {
                return ResourceManager.GetString("NoExistsConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不存在[Member]特性. 的本地化字符串。
        /// </summary>
        internal static string NoMemberAttribute {
            get {
                return ResourceManager.GetString("NoMemberAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没设计页面 的本地化字符串。
        /// </summary>
        internal static string NoPageDesign {
            get {
                return ResourceManager.GetString("NoPageDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持该文件格式 的本地化字符串。
        /// </summary>
        internal static string NotSupportTheFileFormat {
            get {
                return ResourceManager.GetString("NotSupportTheFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;OBJECT&gt;标记是缺少必要的type属性 的本地化字符串。
        /// </summary>
        internal static string ObjectTagMissingTypeAttribute {
            get {
                return ResourceManager.GetString("ObjectTagMissingTypeAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只有Item元素是允许在集合，而不是{0}的内容。 的本地化字符串。
        /// </summary>
        internal static string OnlyAllowItemElements {
            get {
                return ResourceManager.GetString("OnlyAllowItemElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只有Property元素是允许在集合，而不是{0}的内容。 的本地化字符串。
        /// </summary>
        internal static string OnlyAllowPropertyElements {
            get {
                return ResourceManager.GetString("OnlyAllowPropertyElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性{0}不存在类型{1}中。 的本地化字符串。
        /// </summary>
        internal static string PropertyDoesNotExist {
            get {
                return ResourceManager.GetString("PropertyDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性没名称. 的本地化字符串。
        /// </summary>
        internal static string PropertyHasNoName {
            get {
                return ResourceManager.GetString("PropertyHasNoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存更改现有的设计? 的本地化字符串。
        /// </summary>
        internal static string SaveChangeToDesigner {
            get {
                return ResourceManager.GetString("SaveChangeToDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功． 的本地化字符串。
        /// </summary>
        internal static string Successfully {
            get {
                return ResourceManager.GetString("Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示． 的本地化字符串。
        /// </summary>
        internal static string Tip {
            get {
                return ResourceManager.GetString("Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型{0}不能被加载. 的本地化字符串。
        /// </summary>
        internal static string TypeCouldNotBeLoaded {
            get {
                return ResourceManager.GetString("TypeCouldNotBeLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事件绑定服务不存在，所以我们不能绑定任何事件 的本地化字符串。
        /// </summary>
        internal static string UnableBindAnyEvents {
            get {
                return ResourceManager.GetString("UnableBindAnyEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未定义的属主类型. 的本地化字符串。
        /// </summary>
        internal static string UndefinedHostType {
            get {
                return ResourceManager.GetString("UndefinedHostType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知元素类型{0}. 的本地化字符串。
        /// </summary>
        internal static string UnexpectedElementType {
            get {
                return ResourceManager.GetString("UnexpectedElementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未保存的更改. 的本地化字符串。
        /// </summary>
        internal static string UnsavedChanges {
            get {
                return ResourceManager.GetString("UnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件名错误或则该路径不存在该文件 的本地化字符串。
        /// </summary>
        internal static string WrongNameOrFileNotExisted {
            get {
                return ResourceManager.GetString("WrongNameOrFileNotExisted", resourceCulture);
            }
        }
    }
}
