//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICP.WF.Activities.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_CN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_CN() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ICP.WF.Activities.Resources.Resource_CN", typeof(Resource_CN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 完成事件 的本地化字符串。
        /// </summary>
        internal static string AppCompleteEvent {
            get {
                return ResourceManager.GetString("AppCompleteEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化事件 的本地化字符串。
        /// </summary>
        internal static string AppInitEvent {
            get {
                return ResourceManager.GetString("AppInitEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 申请人满足的规则(只有申请人满足该规则,则流程会走该分支.) 的本地化字符串。
        /// </summary>
        internal static string Applicantrules {
            get {
                return ResourceManager.GetString("Applicantrules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 申请任务失败! 的本地化字符串。
        /// </summary>
        internal static string ApplyTaskFailly {
            get {
                return ResourceManager.GetString("ApplyTaskFailly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关联的表单文件 的本地化字符串。
        /// </summary>
        internal static string AssociatedForm {
            get {
                return ResourceManager.GetString("AssociatedForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关联的接口 的本地化字符串。
        /// </summary>
        internal static string AssociatedInterface {
            get {
                return ResourceManager.GetString("AssociatedInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 方法 的本地化字符串。
        /// </summary>
        internal static string AuditorCompleteEvent {
            get {
                return ResourceManager.GetString("AuditorCompleteEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 签收人 的本地化字符串。
        /// </summary>
        internal static string AuditorConditionName {
            get {
                return ResourceManager.GetString("AuditorConditionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 业务交互接口 的本地化字符串。
        /// </summary>
        internal static string BusinessInterface {
            get {
                return ResourceManager.GetString("BusinessInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中文描述-对应后面表单显示的中文标题 的本地化字符串。
        /// </summary>
        internal static string ChineseDescription {
            get {
                return ResourceManager.GetString("ChineseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中文名称 的本地化字符串。
        /// </summary>
        internal static string CName {
            get {
                return ResourceManager.GetString("CName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}]中文标题[{1}]存在重复 的本地化字符串。
        /// </summary>
        internal static string CNameRepeat {
            get {
                return ResourceManager.GetString("CNameRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成事件 的本地化字符串。
        /// </summary>
        internal static string CompleteEvent {
            get {
                return ResourceManager.GetString("CompleteEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条件 的本地化字符串。
        /// </summary>
        internal static string Condition {
            get {
                return ResourceManager.GetString("Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 子分支必须有一个以上. 的本地化字符串。
        /// </summary>
        internal static string ConditionalLessThanOneChildren {
            get {
                return ResourceManager.GetString("ConditionalLessThanOneChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条件分支 的本地化字符串。
        /// </summary>
        internal static string ConditionBranch {
            get {
                return ResourceManager.GetString("ConditionBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 签收人 的本地化字符串。
        /// </summary>
        internal static string ConditionName {
            get {
                return ResourceManager.GetString("ConditionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 申请人条件 的本地化字符串。
        /// </summary>
        internal static string ConditionsOfTheApplicant {
            get {
                return ResourceManager.GetString("ConditionsOfTheApplicant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义 的本地化字符串。
        /// </summary>
        internal static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描述 的本地化字符串。
        /// </summary>
        internal static string Desc {
            get {
                return ResourceManager.GetString("Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序活动 的本地化字符串。
        /// </summary>
        internal static string DescApplicationActivity {
            get {
                return ResourceManager.GetString("DescApplicationActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审核活动 的本地化字符串。
        /// </summary>
        internal static string DescApproveActivity {
            get {
                return ResourceManager.GetString("DescApproveActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调用外部活动 的本地化字符串。
        /// </summary>
        internal static string DescLWCallExternalMethodActivity {
            get {
                return ResourceManager.GetString("DescLWCallExternalMethodActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条件分支 的本地化字符串。
        /// </summary>
        internal static string DescLWIfElseActivity {
            get {
                return ResourceManager.GetString("DescLWIfElseActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送邮件 的本地化字符串。
        /// </summary>
        internal static string DescSendEMailActivity {
            get {
                return ResourceManager.GetString("DescSendEMailActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送系统消息 的本地化字符串。
        /// </summary>
        internal static string DescSendMessageActivity {
            get {
                return ResourceManager.GetString("DescSendMessageActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成事件 的本地化字符串。
        /// </summary>
        internal static string DispCompleteEvent {
            get {
                return ResourceManager.GetString("DispCompleteEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描述 的本地化字符串。
        /// </summary>
        internal static string DispDescription {
            get {
                return ResourceManager.GetString("DispDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内容 的本地化字符串。
        /// </summary>
        internal static string DispMail {
            get {
                return ResourceManager.GetString("DispMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须执行 的本地化字符串。
        /// </summary>
        internal static string DispMust {
            get {
                return ResourceManager.GetString("DispMust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        internal static string DispName {
            get {
                return ResourceManager.GetString("DispName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题 的本地化字符串。
        /// </summary>
        internal static string DispSubject {
            get {
                return ResourceManager.GetString("DispSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮件 的本地化字符串。
        /// </summary>
        internal static string EMail {
            get {
                return ResourceManager.GetString("EMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 英文名称 的本地化字符串。
        /// </summary>
        internal static string EName {
            get {
                return ResourceManager.GetString("EName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}]英文标题[{1}]存在重复 的本地化字符串。
        /// </summary>
        internal static string ENameRepeat {
            get {
                return ResourceManager.GetString("ENameRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 英文描述-对应后面表单显示的英文标题 的本地化字符串。
        /// </summary>
        internal static string EnglishDescription {
            get {
                return ResourceManager.GetString("EnglishDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流程图 的本地化字符串。
        /// </summary>
        internal static string FlowChart {
            get {
                return ResourceManager.GetString("FlowChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关联表单 的本地化字符串。
        /// </summary>
        internal static string FormFile {
            get {
                return ResourceManager.GetString("FormFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}]关联的表单[{1}]不存在. 的本地化字符串。
        /// </summary>
        internal static string FormNotExists {
            get {
                return ResourceManager.GetString("FormNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化事件 的本地化字符串。
        /// </summary>
        internal static string InitEvent {
            get {
                return ResourceManager.GetString("InitEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接口上需要加[ExternalMetodExchangeInterfaceAttribute]特性. 的本地化字符串。
        /// </summary>
        internal static string InterfaceTypeNeedsExternalMetodExchangeInterfaceAttributegeAttribute {
            get {
                return ResourceManager.GetString("InterfaceTypeNeedsExternalMetodExchangeInterfaceAttributegeAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不存在接口. 的本地化字符串。
        /// </summary>
        internal static string InterfaceTypeNotInterface {
            get {
                return ResourceManager.GetString("InterfaceTypeNotInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接收人 的本地化字符串。
        /// </summary>
        internal static string MailConditionName {
            get {
                return ResourceManager.GetString("MailConditionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮件内容 的本地化字符串。
        /// </summary>
        internal static string MailContent {
            get {
                return ResourceManager.GetString("MailContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息内容 的本地化字符串。
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接收人 的本地化字符串。
        /// </summary>
        internal static string MessageConditionName {
            get {
                return ResourceManager.GetString("MessageConditionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息内容 的本地化字符串。
        /// </summary>
        internal static string MessageContent {
            get {
                return ResourceManager.GetString("MessageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 方法名称 的本地化字符串。
        /// </summary>
        internal static string MethodName {
            get {
                return ResourceManager.GetString("MethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 方法名 的本地化字符串。
        /// </summary>
        internal static string MetodName {
            get {
                return ResourceManager.GetString("MetodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否必须执行当前环节 的本地化字符串。
        /// </summary>
        internal static string MustDescription {
            get {
                return ResourceManager.GetString("MustDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}]必须设置[{1}]属性. 的本地化字符串。
        /// </summary>
        internal static string NecessaryToProperty {
            get {
                return ResourceManager.GetString("NecessaryToProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有下一步执行人，请确认部门信息无误 的本地化字符串。
        /// </summary>
        internal static string NoNextAssigned {
            get {
                return ResourceManager.GetString("NoNextAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没通过 的本地化字符串。
        /// </summary>
        internal static string NotThrough {
            get {
                return ResourceManager.GetString("NotThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接收人 的本地化字符串。
        /// </summary>
        internal static string Receiver {
            get {
                return ResourceManager.GetString("Receiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存失败! 的本地化字符串。
        /// </summary>
        internal static string Savefailly {
            get {
                return ResourceManager.GetString("Savefailly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示可以与工作流交互的接口 的本地化字符串。
        /// </summary>
        internal static string ShowingExternalMetodExchangeService {
            get {
                return ResourceManager.GetString("ShowingExternalMetodExchangeService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标准 的本地化字符串。
        /// </summary>
        internal static string Standard {
            get {
                return ResourceManager.GetString("Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 子分支 的本地化字符串。
        /// </summary>
        internal static string Subbranch {
            get {
                return ResourceManager.GetString("Subbranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮件的主题 的本地化字符串。
        /// </summary>
        internal static string SubjectDesc {
            get {
                return ResourceManager.GetString("SubjectDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统变量 的本地化字符串。
        /// </summary>
        internal static string SystemVariable {
            get {
                return ResourceManager.GetString("SystemVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有权限签收当前任务的人 的本地化字符串。
        /// </summary>
        internal static string TaskHolders {
            get {
                return ResourceManager.GetString("TaskHolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置流程标题 的本地化字符串。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序活动 的本地化字符串。
        /// </summary>
        internal static string TitleApplicationActivity {
            get {
                return ResourceManager.GetString("TitleApplicationActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审核活动 的本地化字符串。
        /// </summary>
        internal static string TitleApproveActivity {
            get {
                return ResourceManager.GetString("TitleApproveActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调用外部活动 的本地化字符串。
        /// </summary>
        internal static string TitleLWCallExternalMethodActivity {
            get {
                return ResourceManager.GetString("TitleLWCallExternalMethodActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条件分支 的本地化字符串。
        /// </summary>
        internal static string TitleLWIFElseActivity {
            get {
                return ResourceManager.GetString("TitleLWIFElseActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送邮件 的本地化字符串。
        /// </summary>
        internal static string TitleSendEMailActivity {
            get {
                return ResourceManager.GetString("TitleSendEMailActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送系统消息 的本地化字符串。
        /// </summary>
        internal static string TitleSendMessageActivity {
            get {
                return ResourceManager.GetString("TitleSendMessageActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型不匹配. 的本地化字符串。
        /// </summary>
        internal static string TypeNotMatch {
            get {
                return ResourceManager.GetString("TypeNotMatch", resourceCulture);
            }
        }
    }
}
