//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICP.FCM.AirExport.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FCM_EN_Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FCM_EN_Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ICP.FCM.AirExport.UI.Resources.FCM_EN_Resource", typeof(FCM_EN_Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Add 的本地化字符串。
        /// </summary>
        public static string BarItem_Text_Add {
            get {
                return ResourceManager.GetString("BarItem_Text_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Bill 的本地化字符串。
        /// </summary>
        public static string BarItem_Text_Bill {
            get {
                return ResourceManager.GetString("BarItem_Text_Bill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Cancel 的本地化字符串。
        /// </summary>
        public static string BarItem_Text_Cancel {
            get {
                return ResourceManager.GetString("BarItem_Text_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Check 的本地化字符串。
        /// </summary>
        public static string BarItem_Text_Check {
            get {
                return ResourceManager.GetString("BarItem_Text_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Close 的本地化字符串。
        /// </summary>
        public static string BarItem_Text_Close {
            get {
                return ResourceManager.GetString("BarItem_Text_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 C&amp;opy 的本地化字符串。
        /// </summary>
        public static string BarItem_Text_Copy {
            get {
                return ResourceManager.GetString("BarItem_Text_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Delete 的本地化字符串。
        /// </summary>
        public static string BarItem_Text_Delete {
            get {
                return ResourceManager.GetString("BarItem_Text_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Docume&amp;nt 的本地化字符串。
        /// </summary>
        public static string BarItem_Text_Document {
            get {
                return ResourceManager.GetString("BarItem_Text_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;E_Booking 的本地化字符串。
        /// </summary>
        public static string BarItem_Text_EBooking {
            get {
                return ResourceManager.GetString("BarItem_Text_EBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Edit 的本地化字符串。
        /// </summary>
        public static string BarItem_Text_Edit {
            get {
                return ResourceManager.GetString("BarItem_Text_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E_MBL 的本地化字符串。
        /// </summary>
        public static string BarItem_Text_EMBL {
            get {
                return ResourceManager.GetString("BarItem_Text_EMBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fa&amp;xEmail 的本地化字符串。
        /// </summary>
        public static string BarItem_Text_FaxEmail {
            get {
                return ResourceManager.GetString("BarItem_Text_FaxEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ISF 的本地化字符串。
        /// </summary>
        public static string BarItem_Text_ISF {
            get {
                return ResourceManager.GetString("BarItem_Text_ISF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load Container 的本地化字符串。
        /// </summary>
        public static string BarItem_Text_LoadContainer {
            get {
                return ResourceManager.GetString("BarItem_Text_LoadContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LoadShip 的本地化字符串。
        /// </summary>
        public static string BarItem_Text_LoadShip {
            get {
                return ResourceManager.GetString("BarItem_Text_LoadShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Memo 的本地化字符串。
        /// </summary>
        public static string BarItem_Text_Memo {
            get {
                return ResourceManager.GetString("BarItem_Text_Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;New 的本地化字符串。
        /// </summary>
        public static string BarItem_Text_New {
            get {
                return ResourceManager.GetString("BarItem_Text_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Print 的本地化字符串。
        /// </summary>
        public static string BarItem_Text_Print {
            get {
                return ResourceManager.GetString("BarItem_Text_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Remove 的本地化字符串。
        /// </summary>
        public static string BarItem_Text_Remove {
            get {
                return ResourceManager.GetString("BarItem_Text_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReplyAgent 的本地化字符串。
        /// </summary>
        public static string BarItem_Text_ReplyAgent {
            get {
                return ResourceManager.GetString("BarItem_Text_ReplyAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReplyP&amp;rice 的本地化字符串。
        /// </summary>
        public static string BarItem_Text_ReplyPrice {
            get {
                return ResourceManager.GetString("BarItem_Text_ReplyPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Searc&amp;h 的本地化字符串。
        /// </summary>
        public static string BarItem_Text_ShowSearch {
            get {
                return ResourceManager.GetString("BarItem_Text_ShowSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Truck 的本地化字符串。
        /// </summary>
        public static string BarItem_Text_Truck {
            get {
                return ResourceManager.GetString("BarItem_Text_Truck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;ViewReason 的本地化字符串。
        /// </summary>
        public static string BarItem_Text_ViewReason {
            get {
                return ResourceManager.GetString("BarItem_Text_ViewReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Warehouse 的本地化字符串。
        /// </summary>
        public static string BarItem_Text_Warehouse {
            get {
                return ResourceManager.GetString("BarItem_Text_Warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 C&amp;ustoms 的本地化字符串。
        /// </summary>
        public static string Customs {
            get {
                return ResourceManager.GetString("Customs", resourceCulture);
            }
        }
    }
}
