////////////////////////////////////////////////////////////////////////
//
// user/ICP3ParseStringToString.cs
//
// This file was generated by MapForce 2011r2.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the MapForce Documentation for further details.
// http://www.altova.com/mapforce
//
////////////////////////////////////////////////////////////////////////

using System.Collections;


// application.libraries
namespace COSCO.Booking

{
	
	public class ICP3ParseStringToString : Altova.TraceProvider 
	{



        #region Members
        // instances
        // members
        protected object m_ToStringTargetParameter;
        #endregion //Members

        class seq1_Main : IEnumerable
        {
            Altova.Functions.RuntimeContext var1_context;
            string var2_valString;
            int var3_length;

            public seq1_Main(
                Altova.Functions.RuntimeContext var1_context,
                string var2_valString,
                int var3_length
                )
            {
                this.var1_context = var1_context;
                this.var2_valString = var2_valString;
                this.var3_length = var3_length;
            }

            public IEnumerator GetEnumerator() { return new Enumerator(this); }

            class Enumerator : Altova.Mapforce.IMFEnumerator
            {
                int state = 1;
                object current = null;
                int pos = 0;
                seq1_Main closure;
                string var9_const_;
                string var8_const_ICP3ParseStringToStr;
                string var5_const_http___schemas_xmlso;
                Altova.Types.QName var7_create_qname;
                Altova.Types.QName var6_create_qname;
                IEnumerator var4_map_filter_elements;
                IEnumerator var10_map_filter_elements;
                string var12_const_http___www_CityOcean;
                IEnumerator var11_map_filter_elements;
                IEnumerator var13_map_filter_elements;
                public Enumerator(seq1_Main closure)
                {
                    this.closure = closure;
                }

                public void Reset() { state = 0; pos = 0; }
                public int Position { get { return pos; } }
                public object Current { get { return current; } }

                public bool MoveNext()
                {
                    while (state != 0)
                    {
                        switch (state)
                        {
                            case 1:
                                state = 5;
                                var9_const_ = ("");
                                var8_const_ICP3ParseStringToStr = ("ICP3ParseStringToString");
                                var5_const_http___schemas_xmlso = ("http://schemas.xmlsoap.org/soap/envelope/");
                                var7_create_qname = (Altova.Functions.Core.CreateQName("Body", var5_const_http___schemas_xmlso));
                                var6_create_qname = (Altova.Functions.Core.CreateQName("Envelope", var5_const_http___schemas_xmlso));
                                var4_map_filter_elements = (Altova.Functions.Core.FilterElements(Altova.Functions.Core.CreateQName("Fault", var5_const_http___schemas_xmlso), (Altova.Mapforce.IMFNode)Altova.Functions.Core.First(Altova.Functions.Core.FilterElements(var7_create_qname, (Altova.Mapforce.IMFNode)Altova.Functions.Core.First(Altova.Functions.Core.FilterElements(var6_create_qname, Altova.Xml.InternalXML.CallWebservice(Altova.Functions.Core.CreateElement(var6_create_qname, Altova.Functions.Core.Box(Altova.Functions.Core.CreateElement(var7_create_qname, Altova.Functions.Core.Box(Altova.Functions.Core.CreateElement(Altova.Functions.Core.CreateQName(var8_const_ICP3ParseStringToStr, "http://www.CityOcean.com/"), (new seq2_create_element(closure.var2_valString, closure.var3_length))))))), "ICP3EDIService", var8_const_ICP3ParseStringToStr, Altova.Functions.Lang.StringAsQName("{http://www.CityOcean.com/}ICP3ParseStringToString"), "http://www.CityOcean.com/ICP3ParseStringToString", "http://app.cityocean.com:83/ICP3EDIService.asmx", "document", var9_const_, var9_const_, 0, var9_const_, var9_const_, 1))))))).GetEnumerator();
                                goto case 5;
                            case 5:
                                state = 9;
                                if (!var4_map_filter_elements.MoveNext()) { state = 6; goto case 6; }
                                var10_map_filter_elements = (Altova.Functions.Core.FilterElements(Altova.Functions.Core.CreateQName("detail", var9_const_), (Altova.Mapforce.IMFNode)(var4_map_filter_elements.Current))).GetEnumerator();
                                goto case 9;
                            case 6:
                                state = 19;
                                Altova.Mapforce.MFEnumerator.Dispose(var4_map_filter_elements); var4_map_filter_elements = null;
                                var12_const_http___www_CityOcean = ("http://www.CityOcean.com/");
                                var11_map_filter_elements = (Altova.Functions.Core.FilterElements(Altova.Functions.Core.CreateQName("ICP3ParseStringToStringResponse", var12_const_http___www_CityOcean), (Altova.Mapforce.IMFNode)Altova.Functions.Core.First(Altova.Functions.Core.FilterElements(var7_create_qname, (Altova.Mapforce.IMFNode)Altova.Functions.Core.First(Altova.Functions.Core.FilterElements(var6_create_qname, Altova.Xml.InternalXML.CallWebservice(Altova.Functions.Core.CreateElement(var6_create_qname, Altova.Functions.Core.Box(Altova.Functions.Core.CreateElement(var7_create_qname, Altova.Functions.Core.Box(Altova.Functions.Core.CreateElement(Altova.Functions.Core.CreateQName(var8_const_ICP3ParseStringToStr, var12_const_http___www_CityOcean), (new seq2_create_element(closure.var2_valString, closure.var3_length))))))), "ICP3EDIService", var8_const_ICP3ParseStringToStr, Altova.Functions.Lang.StringAsQName("{http://www.CityOcean.com/}ICP3ParseStringToString"), "http://www.CityOcean.com/ICP3ParseStringToString", "http://app.cityocean.com:83/ICP3EDIService.asmx", "document", var9_const_, var9_const_, 0, var9_const_, var9_const_, 1))))))).GetEnumerator();
                                goto case 19;
                            case 9:
                                state = 9;
                                if (!var10_map_filter_elements.MoveNext()) { state = 10; goto case 10; }
                                Altova.Functions.Core.ThrowUserException(Altova.CoreTypes.NodeToString((Altova.Mapforce.IMFNode)(var10_map_filter_elements.Current)));
                                goto case 9;
                            case 10:
                                state = 5;
                                Altova.Mapforce.MFEnumerator.Dispose(var10_map_filter_elements); var10_map_filter_elements = null;
                                goto case 5;
                            case 19:
                                state = 23;
                                if (!var11_map_filter_elements.MoveNext()) { state = 20; goto case 20; }
                                var13_map_filter_elements = (Altova.Functions.Core.FilterElements(Altova.Functions.Core.CreateQName("ICP3ParseStringToStringResult", var12_const_http___www_CityOcean), (Altova.Mapforce.IMFNode)(var11_map_filter_elements.Current))).GetEnumerator();
                                goto case 23;
                            case 20:
                                state = 0;
                                Altova.Mapforce.MFEnumerator.Dispose(var11_map_filter_elements); var11_map_filter_elements = null;
                                return false;
                            case 23:
                                state = 23;
                                if (!var13_map_filter_elements.MoveNext()) { state = 24; goto case 24; }
                                current = Altova.CoreTypes.NodeToString((Altova.Mapforce.IMFNode)(var13_map_filter_elements.Current));
                                pos++;
                                return true;
                            case 24:
                                state = 19;
                                Altova.Mapforce.MFEnumerator.Dispose(var13_map_filter_elements); var13_map_filter_elements = null;
                                goto case 19;
                        }
                    }
                    return false;
                }

                public void Dispose()
                {
                    Altova.Mapforce.MFEnumerator.Dispose(var10_map_filter_elements); var10_map_filter_elements = null;
                    Altova.Mapforce.MFEnumerator.Dispose(var4_map_filter_elements); var4_map_filter_elements = null;
                    Altova.Mapforce.MFEnumerator.Dispose(var13_map_filter_elements); var13_map_filter_elements = null;
                    Altova.Mapforce.MFEnumerator.Dispose(var11_map_filter_elements); var11_map_filter_elements = null;
                }
            }

        }
        class seq2_create_element : IEnumerable
        {
            string var1_valString;
            int var4_length;

            public seq2_create_element(
                string var1_valString,
                int var4_length
                )
            {
                this.var1_valString = var1_valString;
                this.var4_length = var4_length;
            }

            public IEnumerator GetEnumerator() { return new Enumerator(this); }

            class Enumerator : Altova.Mapforce.IMFEnumerator
            {
                int state = 1;
                object current = null;
                int pos = 0;
                seq2_create_element closure;
                string var3_const_;
                string var2_const_http___www_CityOcean;
                public Enumerator(seq2_create_element closure)
                {
                    this.closure = closure;
                }

                public void Reset() { state = 0; pos = 0; }
                public int Position { get { return pos; } }
                public object Current { get { return current; } }

                public bool MoveNext()
                {
                    while (state != 0)
                    {
                        switch (state)
                        {
                            case 1:
                                state = 5;
                                var3_const_ = ("");
                                var2_const_http___www_CityOcean = ("http://www.CityOcean.com/");
                                current = Altova.Functions.Core.CreateElementWithPrefix(Altova.Functions.Core.CreateQName("valString", var2_const_http___www_CityOcean), var3_const_, Altova.Functions.Core.Box(closure.var1_valString));
                                pos++;
                                return true;
                            case 5:
                                state = 0;
                                current = Altova.Functions.Core.CreateElementWithPrefix(Altova.Functions.Core.CreateQName("length", var2_const_http___www_CityOcean), var3_const_, Altova.Functions.Core.Box(Altova.CoreTypes.DecimalToString(Altova.CoreTypes.LongToDecimal(Altova.CoreTypes.IntToLong(closure.var4_length)))));
                                pos++;
                                return true;
                        }
                    }
                    return false;
                }

                public void Dispose()
                {
                }
            }

        }


        public static IEnumerable Create(
            Altova.Functions.RuntimeContext var1_context,
            string var2_valString,
            int var3_length
            )
        {
            return new seq1_Main(
                var1_context,
                var2_valString,
                var3_length
                );

        }



  } 
}
