////////////////////////////////////////////////////////////////////////
//
// vmf/vmf3_inputtoresult.cs
//
// This file was generated by MapForce 2011r2.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the MapForce Documentation for further details.
// http://www.altova.com/mapforce
//
////////////////////////////////////////////////////////////////////////

using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Xml;
using Altova.Types;
using Altova.Xml;
using Altova.Functions;
using Altova.TextParser;


using Envelope; // application.libraries
namespace vmf
{

    public class vmf3_inputtoresult : Altova.TraceProvider
    {




        class Main : IEnumerable
        {
            int var1_input;

            public Main(
                int var1_input
                )
            {
                this.var1_input = var1_input;
            }

            public IEnumerator GetEnumerator() { return Altova.Mapforce.MFEmptySequence.Instance.GetEnumerator(); }

        }


        public static IEnumerable Create(
            int var1_input
            )
        {

            object o = hash[var1_input];
            if (o != null)
                return new Altova.Mapforce.MFSingletonSequence(o);
            else
                return Altova.Mapforce.MFEmptySequence.Instance;

        }

        static Hashtable hash = new Hashtable();
        static vmf3_inputtoresult()
        {
            hash[0] = "";
            hash[1] = "706";
            hash[2] = "706";
            hash[3] = "710";
        }

    } 
}
