//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LongWin.DataWarehouseReport.WinUI {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DWReportResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DWReportResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LongWin.DataWarehouseReport.WinUI.Resources.DWReportResources", typeof(DWReportResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 EName 的本地化字符串。
        /// </summary>
        internal static string CName {
            get {
                return ResourceManager.GetString("CName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last Month 的本地化字符串。
        /// </summary>
        internal static string 上个月 {
            get {
                return ResourceManager.GetString("上个月", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Job Information Detail 的本地化字符串。
        /// </summary>
        internal static string 业务信息详细 {
            get {
                return ResourceManager.GetString("业务信息详细", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Company 的本地化字符串。
        /// </summary>
        internal static string 业务发生地 {
            get {
                return ResourceManager.GetString("业务发生地", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sales 的本地化字符串。
        /// </summary>
        internal static string 业务员 {
            get {
                return ResourceManager.GetString("业务员", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Department 的本地化字符串。
        /// </summary>
        internal static string 业务所属部门 {
            get {
                return ResourceManager.GetString("业务所属部门", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Job Date 的本地化字符串。
        /// </summary>
        internal static string 业务时间 {
            get {
                return ResourceManager.GetString("业务时间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Return Commission Report 的本地化字符串。
        /// </summary>
        internal static string 业务管理成本统计表 {
            get {
                return ResourceManager.GetString("业务管理成本统计表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Job Type 的本地化字符串。
        /// </summary>
        internal static string 业务类型 {
            get {
                return ResourceManager.GetString("业务类型", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cost-Individual Expense 的本地化字符串。
        /// </summary>
        internal static string 个人帐单 {
            get {
                return ResourceManager.GetString("个人帐单", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loss 的本地化字符串。
        /// </summary>
        internal static string 亏损 {
            get {
                return ResourceManager.GetString("亏损", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Destination 的本地化字符串。
        /// </summary>
        internal static string 交货地 {
            get {
                return ResourceManager.GetString("交货地", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This Year 的本地化字符串。
        /// </summary>
        internal static string 今年 {
            get {
                return ResourceManager.GetString("今年", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Agent 的本地化字符串。
        /// </summary>
        internal static string 代理 {
            get {
                return ResourceManager.GetString("代理", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Agent 的本地化字符串。
        /// </summary>
        internal static string 代理人 {
            get {
                return ResourceManager.GetString("代理人", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Agent Statement Report 的本地化字符串。
        /// </summary>
        internal static string 代理帐款表 {
            get {
                return ResourceManager.GetString("代理帐款表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ALL 的本地化字符串。
        /// </summary>
        internal static string 全部 {
            get {
                return ResourceManager.GetString("全部", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 COMPANY 的本地化字符串。
        /// </summary>
        internal static string 公司货 {
            get {
                return ResourceManager.GetString("公司货", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OTHER 的本地化字符串。
        /// </summary>
        internal static string 其他业务 {
            get {
                return ResourceManager.GetString("其他业务", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OTHER 的本地化字符串。
        /// </summary>
        internal static string 其它业务 {
            get {
                return ResourceManager.GetString("其它业务", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Voucher List 的本地化字符串。
        /// </summary>
        internal static string 凭证明细表 {
            get {
                return ResourceManager.GetString("凭证明细表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        internal static string 出口业务 {
            get {
                return ResourceManager.GetString("出口业务", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Date 的本地化字符串。
        /// </summary>
        internal static string 创建时间 {
            get {
                return ResourceManager.GetString("创建时间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Profit Same Term Compare Analysis 的本地化字符串。
        /// </summary>
        internal static string 利润同期对比图 {
            get {
                return ResourceManager.GetString("利润同期对比图", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Profit Constitutes Analysis 的本地化字符串。
        /// </summary>
        internal static string 利润组成分析表 {
            get {
                return ResourceManager.GetString("利润组成分析表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Profit Trend Analysis 的本地化字符串。
        /// </summary>
        internal static string 利润趋势表 {
            get {
                return ResourceManager.GetString("利润趋势表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Per Container Of Profit Graph 的本地化字符串。
        /// </summary>
        internal static string 单箱利润表 {
            get {
                return ResourceManager.GetString("单箱利润表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last Year 的本地化字符串。
        /// </summary>
        internal static string 去年 {
            get {
                return ResourceManager.GetString("去年", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drivers 的本地化字符串。
        /// </summary>
        internal static string 司机 {
            get {
                return ResourceManager.GetString("司机", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 S/C No. 的本地化字符串。
        /// </summary>
        internal static string 合约号 {
            get {
                return ResourceManager.GetString("合约号", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NVOCC 的本地化字符串。
        /// </summary>
        internal static string 同行货 {
            get {
                return ResourceManager.GetString("同行货", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        internal static string 否 {
            get {
                return ResourceManager.GetString("否", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Employee 的本地化字符串。
        /// </summary>
        internal static string 员工 {
            get {
                return ResourceManager.GetString("员工", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account Voucher 的本地化字符串。
        /// </summary>
        internal static string 实收实付凭证 {
            get {
                return ResourceManager.GetString("实收实付凭证", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customer 的本地化字符串。
        /// </summary>
        internal static string 客户 {
            get {
                return ResourceManager.GetString("客户", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        internal static string 常规 {
            get {
                return ResourceManager.GetString("常规", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Year 的本地化字符串。
        /// </summary>
        internal static string 年 {
            get {
                return ResourceManager.GetString("年", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account Payable Report 的本地化字符串。
        /// </summary>
        internal static string 应付帐款表 {
            get {
                return ResourceManager.GetString("应付帐款表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aging Statement 的本地化字符串。
        /// </summary>
        internal static string 应收帐款帐龄表 {
            get {
                return ResourceManager.GetString("应收帐款帐龄表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account Receivable Report 的本地化字符串。
        /// </summary>
        internal static string 应收帐款表 {
            get {
                return ResourceManager.GetString("应收帐款表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Surplus Statement Report 的本地化字符串。
        /// </summary>
        internal static string 应收应付盈余表 {
            get {
                return ResourceManager.GetString("应收应付盈余表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shipper 的本地化字符串。
        /// </summary>
        internal static string 往来单位 {
            get {
                return ResourceManager.GetString("往来单位", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cost Constitutes Analysis 的本地化字符串。
        /// </summary>
        internal static string 成本分析图 {
            get {
                return ResourceManager.GetString("成本分析图", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cost Same Term Compare Analysis 的本地化字符串。
        /// </summary>
        internal static string 成本同期比较分析图 {
            get {
                return ResourceManager.GetString("成本同期比较分析图", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cost Direction Analysis 的本地化字符串。
        /// </summary>
        internal static string 成本趋势分析图 {
            get {
                return ResourceManager.GetString("成本趋势分析图", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Carrier 的本地化字符串。
        /// </summary>
        internal static string 承运人 {
            get {
                return ResourceManager.GetString("承运人", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 APPLY TO CUSTOMS 的本地化字符串。
        /// </summary>
        internal static string 报关业务 {
            get {
                return ResourceManager.GetString("报关业务", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LCL 的本地化字符串。
        /// </summary>
        internal static string 拼箱业务 {
            get {
                return ResourceManager.GetString("拼箱业务", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AGENT 的本地化字符串。
        /// </summary>
        internal static string 指定货 {
            get {
                return ResourceManager.GetString("指定货", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sales Type 的本地化字符串。
        /// </summary>
        internal static string 揽货方式 {
            get {
                return ResourceManager.GetString("揽货方式", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workload Statistics 的本地化字符串。
        /// </summary>
        internal static string 操作工作量统计 {
            get {
                return ResourceManager.GetString("操作工作量统计", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BULK 的本地化字符串。
        /// </summary>
        internal static string 散货业务 {
            get {
                return ResourceManager.GetString("散货业务", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date 的本地化字符串。
        /// </summary>
        internal static string 日期 {
            get {
                return ResourceManager.GetString("日期", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        internal static string 是 {
            get {
                return ResourceManager.GetString("是", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 More 的本地化字符串。
        /// </summary>
        internal static string 更多 {
            get {
                return ResourceManager.GetString("更多", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Month 的本地化字符串。
        /// </summary>
        internal static string 月 {
            get {
                return ResourceManager.GetString("月", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This Month 的本地化字符串。
        /// </summary>
        internal static string 本月 {
            get {
                return ResourceManager.GetString("本月", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        internal static string 查询 {
            get {
                return ResourceManager.GetString("查询", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Profit 的本地化字符串。
        /// </summary>
        internal static string 盈利 {
            get {
                return ResourceManager.GetString("盈利", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SALES 的本地化字符串。
        /// </summary>
        internal static string 直客货 {
            get {
                return ResourceManager.GetString("直客货", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AIR 的本地化字符串。
        /// </summary>
        internal static string 空运业务 {
            get {
                return ResourceManager.GetString("空运业务", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Volume and Profit By Total 的本地化字符串。
        /// </summary>
        internal static string 箱量利润统计表 {
            get {
                return ResourceManager.GetString("箱量利润统计表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Volume and Profit By Detail 的本地化字符串。
        /// </summary>
        internal static string 箱量利润详细表 {
            get {
                return ResourceManager.GetString("箱量利润详细表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TEU Same Term Compare Analysis 的本地化字符串。
        /// </summary>
        internal static string 箱量同期对比图 {
            get {
                return ResourceManager.GetString("箱量同期对比图", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Volume Trend Analysis 的本地化字符串。
        /// </summary>
        internal static string 箱量趋势表 {
            get {
                return ResourceManager.GetString("箱量趋势表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Department 的本地化字符串。
        /// </summary>
        internal static string 组织结构 {
            get {
                return ResourceManager.GetString("组织结构", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Analysis Of Operating Statements 的本地化字符串。
        /// </summary>
        internal static string 经营状况分析表 {
            get {
                return ResourceManager.GetString("经营状况分析表", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Air Company 的本地化字符串。
        /// </summary>
        internal static string 航空公司 {
            get {
                return ResourceManager.GetString("航空公司", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Line 的本地化字符串。
        /// </summary>
        internal static string 航线 {
            get {
                return ResourceManager.GetString("航线", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ship Owner 的本地化字符串。
        /// </summary>
        internal static string 船公司 {
            get {
                return ResourceManager.GetString("船公司", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 POL 的本地化字符串。
        /// </summary>
        internal static string 装货港 {
            get {
                return ResourceManager.GetString("装货港", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Billing Voucher 的本地化字符串。
        /// </summary>
        internal static string 计帐凭证 {
            get {
                return ResourceManager.GetString("计帐凭证", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pls Select Job Type 的本地化字符串。
        /// </summary>
        internal static string 请选择业务类型 {
            get {
                return ResourceManager.GetString("请选择业务类型", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select division 的本地化字符串。
        /// </summary>
        internal static string 请选择分组条件 {
            get {
                return ResourceManager.GetString("请选择分组条件", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pls select department 的本地化字符串。
        /// </summary>
        internal static string 请选择组织结构 {
            get {
                return ResourceManager.GetString("请选择组织结构", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fee Date 的本地化字符串。
        /// </summary>
        internal static string 费用期间 {
            get {
                return ResourceManager.GetString("费用期间", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cost Item 的本地化字符串。
        /// </summary>
        internal static string 费用项目 {
            get {
                return ResourceManager.GetString("费用项目", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IMPORT 的本地化字符串。
        /// </summary>
        internal static string 进口业务 {
            get {
                return ResourceManager.GetString("进口业务", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Department 的本地化字符串。
        /// </summary>
        internal static string 部门 {
            get {
                return ResourceManager.GetString("部门", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TRAILER 的本地化字符串。
        /// </summary>
        internal static string 集运业务 {
            get {
                return ResourceManager.GetString("集运业务", resourceCulture);
            }
        }
    }
}
