////////////////////////////////////////////////////////////////////////
//
// vmf/vmf2_inputtoresult.cs
//
// This file was generated by MapForce 2011r2.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the MapForce Documentation for further details.
// http://www.altova.com/mapforce
//
////////////////////////////////////////////////////////////////////////

using System.Collections;


// application.libraries
namespace HANJIN.SI

{
	
	public class vmf2_inputtoresult : Altova.TraceProvider 
	{




	class Main : IEnumerable
	{
		bool var1_input;
	
		public Main(
			bool var1_input
			)
		{
			this.var1_input = var1_input;
		}

		public IEnumerator GetEnumerator() { return Altova.Mapforce.MFEmptySequence.Instance.GetEnumerator(); }
				
	}


	public static IEnumerable Create(
		bool var1_input
		)
	{

		object o = hash[var1_input];
		if (o != null)
			return new Altova.Mapforce.MFSingletonSequence(o);
		else
			return Altova.Mapforce.MFEmptySequence.Instance;

	}

		static Hashtable hash = new Hashtable();
		static vmf2_inputtoresult()
		{
			hash[Altova.CoreTypes.ParseBoolean("true")] = "THIS SHIPMENT CONTAINS WOOD PACKING MATERIALS";	
			hash[Altova.CoreTypes.ParseBoolean("false")] = "THIS SHIPMENT CONTAINS NO WOOD PACKING MATERIALS";	
		}

  } 
}
