//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICP.WF.Controls.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceCN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceCN() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ICP.WF.Controls.Resources.ResourceCN", typeof(ResourceCN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 会计科目数据源 的本地化字符串。
        /// </summary>
        internal static string AccountSubBindingSource {
            get {
                return ResourceManager.GetString("AccountSubBindingSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 会计科目 的本地化字符串。
        /// </summary>
        internal static string AccountSubBindingSourceTitle {
            get {
                return ResourceManager.GetString("AccountSubBindingSourceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可为空 的本地化字符串。
        /// </summary>
        internal static string AllowNull {
            get {
                return ResourceManager.GetString("AllowNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 增加行 的本地化字符串。
        /// </summary>
        internal static string AllowUserToAddRows {
            get {
                return ResourceManager.GetString("AllowUserToAddRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除行 的本地化字符串。
        /// </summary>
        internal static string AllowUserToDeleteRows {
            get {
                return ResourceManager.GetString("AllowUserToDeleteRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移动列顺序 的本地化字符串。
        /// </summary>
        internal static string AllowUserToOrderColumns {
            get {
                return ResourceManager.GetString("AllowUserToOrderColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调整列大小 的本地化字符串。
        /// </summary>
        internal static string AllowUserToResizeColumns {
            get {
                return ResourceManager.GetString("AllowUserToResizeColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调整行大小 的本地化字符串。
        /// </summary>
        internal static string AllowUserToResizeRows {
            get {
                return ResourceManager.GetString("AllowUserToResizeRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停靠 的本地化字符串。
        /// </summary>
        internal static string Anchor {
            get {
                return ResourceManager.GetString("Anchor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成单号 的本地化字符串。
        /// </summary>
        internal static string AutoGeneratorNumber {
            get {
                return ResourceManager.GetString("AutoGeneratorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 背景颜色 的本地化字符串。
        /// </summary>
        internal static string BackColor {
            get {
                return ResourceManager.GetString("BackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 背景颜色 的本地化字符串。
        /// </summary>
        internal static string BackgroundColor {
            get {
                return ResourceManager.GetString("BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 银行帐号数据源 的本地化字符串。
        /// </summary>
        internal static string BankBindingSourceDesc {
            get {
                return ResourceManager.GetString("BankBindingSourceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 银行帐号 的本地化字符串。
        /// </summary>
        internal static string BankBindingSourceTitle {
            get {
                return ResourceManager.GetString("BankBindingSourceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基础 的本地化字符串。
        /// </summary>
        internal static string Base {
            get {
                return ResourceManager.GetString("Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 粗体 的本地化字符串。
        /// </summary>
        internal static string Bold {
            get {
                return ResourceManager.GetString("Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控件显示的标题 的本地化字符串。
        /// </summary>
        internal static string Caption {
            get {
                return ResourceManager.GetString("Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中文显示成员 的本地化字符串。
        /// </summary>
        internal static string CDisplayMember {
            get {
                return ResourceManager.GetString("CDisplayMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中文文本显示成员 的本地化字符串。
        /// </summary>
        internal static string CFullDisplayMember {
            get {
                return ResourceManager.GetString("CFullDisplayMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Root--&gt;定级节点,Assets--资产,Liabilities--&gt;负债, OwnerEquity--&gt;所有者权益,Costs--&gt;成本,Income--损益,Expense--&gt;费用 的本地化字符串。
        /// </summary>
        internal static string ChargingGroupTypeDescription {
            get {
                return ResourceManager.GetString("ChargingGroupTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复选按钮 的本地化字符串。
        /// </summary>
        internal static string CheckBox {
            get {
                return ResourceManager.GetString("CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提供一项选择，如“真/假”或“是/否” 的本地化字符串。
        /// </summary>
        internal static string CheckBoxDesc {
            get {
                return ResourceManager.GetString("CheckBoxDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复选按钮 的本地化字符串。
        /// </summary>
        internal static string CheckBoxTitle {
            get {
                return ResourceManager.GetString("CheckBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复选按钮 的本地化字符串。
        /// </summary>
        internal static string CheckedDesc {
            get {
                return ResourceManager.GetString("CheckedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中文环境下,显示的标题 的本地化字符串。
        /// </summary>
        internal static string ChineseDescription {
            get {
                return ResourceManager.GetString("ChineseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列头模式 的本地化字符串。
        /// </summary>
        internal static string ColumnHeadersHeightSizeMode {
            get {
                return ResourceManager.GetString("ColumnHeadersHeightSizeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入列头 的本地化字符串。
        /// </summary>
        internal static string ColumnHeaderTextIsNull {
            get {
                return ResourceManager.GetString("ColumnHeaderTextIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列名 的本地化字符串。
        /// </summary>
        internal static string ColumnName {
            get {
                return ResourceManager.GetString("ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入列名 的本地化字符串。
        /// </summary>
        internal static string ColumnNameIsNull {
            get {
                return ResourceManager.GetString("ColumnNameIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{ 0 }]列名存在重复[{ 1 }] 的本地化字符串。
        /// </summary>
        internal static string ColumnNameRepeat {
            get {
                return ResourceManager.GetString("ColumnNameRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列集合 的本地化字符串。
        /// </summary>
        internal static string Columns {
            get {
                return ResourceManager.GetString("Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 跨列 的本地化字符串。
        /// </summary>
        internal static string ColumnSpan {
            get {
                return ResourceManager.GetString("ColumnSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列宽 的本地化字符串。
        /// </summary>
        internal static string ColumnsWidth {
            get {
                return ResourceManager.GetString("ColumnsWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择列类型 的本地化字符串。
        /// </summary>
        internal static string ColumnTypsIsNull {
            get {
                return ResourceManager.GetString("ColumnTypsIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组合框 的本地化字符串。
        /// </summary>
        internal static string ComboBox {
            get {
                return ResourceManager.GetString("ComboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下拉树 的本地化字符串。
        /// </summary>
        internal static string ComboBoxTreeViewDesc {
            get {
                return ResourceManager.GetString("ComboBoxTreeViewDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据类型 的本地化字符串。
        /// </summary>
        internal static string ComboBoxType {
            get {
                return ResourceManager.GetString("ComboBoxType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户可从数据列表中选择一项 的本地化字符串。
        /// </summary>
        internal static string ComBoxDesc {
            get {
                return ResourceManager.GetString("ComBoxDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下拉框 的本地化字符串。
        /// </summary>
        internal static string ComBoxTitle {
            get {
                return ResourceManager.GetString("ComBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公司 的本地化字符串。
        /// </summary>
        internal static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公司数据 的本地化字符串。
        /// </summary>
        internal static string CompanyBindingSource {
            get {
                return ResourceManager.GetString("CompanyBindingSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公司数据 的本地化字符串。
        /// </summary>
        internal static string CompanyBindingSourceDesc {
            get {
                return ResourceManager.GetString("CompanyBindingSourceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公司数据列表. 的本地化字符串。
        /// </summary>
        internal static string CompanyBindingSourceDesCompanyBindingSourceDesc {
            get {
                return ResourceManager.GetString("CompanyBindingSourceDesCompanyBindingSourceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公司 的本地化字符串。
        /// </summary>
        internal static string CompanyBindingSourceTitle {
            get {
                return ResourceManager.GetString("CompanyBindingSourceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All-&gt;所有公司,Company-&gt;当前用户所公司,Department-&gt;当前用户所在部门. 的本地化字符串。
        /// </summary>
        internal static string CompanySourceTypeDescription {
            get {
                return ResourceManager.GetString("CompanySourceTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控件数据源里面的属性 的本地化字符串。
        /// </summary>
        internal static string ControlDataSourceProperties {
            get {
                return ResourceManager.GetString("ControlDataSourceProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控件事件 的本地化字符串。
        /// </summary>
        internal static string Controlevent {
            get {
                return ResourceManager.GetString("Controlevent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控件属性 的本地化字符串。
        /// </summary>
        internal static string ControlProperty {
            get {
                return ResourceManager.GetString("ControlProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All--&gt;全部,ManagementCost--管理成本,BusinessCost--&gt;业务费用, TransportCost--&gt;运输成本 的本地化字符串。
        /// </summary>
        internal static string CostTypeDescription {
            get {
                return ResourceManager.GetString("CostTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中文标题 的本地化字符串。
        /// </summary>
        internal static string CText {
            get {
                return ResourceManager.GetString("CText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}]中文标题存在重复[{1}] 的本地化字符串。
        /// </summary>
        internal static string CTextRepeat {
            get {
                return ResourceManager.GetString("CTextRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 币种 的本地化字符串。
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 币种数据 的本地化字符串。
        /// </summary>
        internal static string CurrencyBindingSource {
            get {
                return ResourceManager.GetString("CurrencyBindingSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 币种 的本地化字符串。
        /// </summary>
        internal static string CurrencyBindingSourceTitle {
            get {
                return ResourceManager.GetString("CurrencyBindingSourceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义 的本地化字符串。
        /// </summary>
        internal static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据 的本地化字符串。
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据绑定 的本地化字符串。
        /// </summary>
        internal static string DataBinding {
            get {
                return ResourceManager.GetString("DataBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据列定义 的本地化字符串。
        /// </summary>
        internal static string DataCustom {
            get {
                return ResourceManager.GetString("DataCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据字典数据源 的本地化字符串。
        /// </summary>
        internal static string DataDictionariesSourceDesc {
            get {
                return ResourceManager.GetString("DataDictionariesSourceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据字典 的本地化字符串。
        /// </summary>
        internal static string DataDictionariesSourceTitle {
            get {
                return ResourceManager.GetString("DataDictionariesSourceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据字典类型 的本地化字符串。
        /// </summary>
        internal static string DataDictionaryTypeDescription {
            get {
                return ResourceManager.GetString("DataDictionaryTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网格 的本地化字符串。
        /// </summary>
        internal static string DataGridView {
            get {
                return ResourceManager.GetString("DataGridView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提供用来显示数据的可自定义表 的本地化字符串。
        /// </summary>
        internal static string DataGridViewDesc {
            get {
                return ResourceManager.GetString("DataGridViewDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据列表 的本地化字符串。
        /// </summary>
        internal static string DataGridViewTitle {
            get {
                return ResourceManager.GetString("DataGridViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据属性 的本地化字符串。
        /// </summary>
        internal static string DataProperty {
            get {
                return ResourceManager.GetString("DataProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 范围 的本地化字符串。
        /// </summary>
        internal static string DataScope {
            get {
                return ResourceManager.GetString("DataScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据源 的本地化字符串。
        /// </summary>
        internal static string DataSource {
            get {
                return ResourceManager.GetString("DataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日期 的本地化字符串。
        /// </summary>
        internal static string DatePicker {
            get {
                return ResourceManager.GetString("DatePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用来让用户选择日期和时间，并以指定的格式显示此日期和时间 的本地化字符串。
        /// </summary>
        internal static string DatePickerDesc {
            get {
                return ResourceManager.GetString("DatePickerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间框 的本地化字符串。
        /// </summary>
        internal static string DatePickerTitle {
            get {
                return ResourceManager.GetString("DatePickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日期 的本地化字符串。
        /// </summary>
        internal static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认值 的本地化字符串。
        /// </summary>
        internal static string DefaultValue {
            get {
                return ResourceManager.GetString("DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 学历 的本地化字符串。
        /// </summary>
        internal static string DegreeBindingSourceDesc {
            get {
                return ResourceManager.GetString("DegreeBindingSourceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 学历 的本地化字符串。
        /// </summary>
        internal static string DegreeBindingSourceTitle {
            get {
                return ResourceManager.GetString("DegreeBindingSourceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置控件共包含多少列 的本地化字符串。
        /// </summary>
        internal static string DescColumnCount {
            get {
                return ResourceManager.GetString("DescColumnCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置列的宽度 的本地化字符串。
        /// </summary>
        internal static string DescColumnsWidth {
            get {
                return ResourceManager.GetString("DescColumnsWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置控件共包含多少行 的本地化字符串。
        /// </summary>
        internal static string DescRowCount {
            get {
                return ResourceManager.GetString("DescRowCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 滚动条显示方式 的本地化字符串。
        /// </summary>
        internal static string DescScrollBars {
            get {
                return ResourceManager.GetString("DescScrollBars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置控件大小 的本地化字符串。
        /// </summary>
        internal static string DescSize {
            get {
                return ResourceManager.GetString("DescSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置控件只否可以编辑 的本地化字符串。
        /// </summary>
        internal static string DescTabIndex {
            get {
                return ResourceManager.GetString("DescTabIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许空 的本地化字符串。
        /// </summary>
        internal static string DispAllowNull {
            get {
                return ResourceManager.GetString("DispAllowNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置控件的背景颜色 的本地化字符串。
        /// </summary>
        internal static string DispBackColor {
            get {
                return ResourceManager.GetString("DispBackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题 的本地化字符串。
        /// </summary>
        internal static string DispCaption {
            get {
                return ResourceManager.GetString("DispCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择 的本地化字符串。
        /// </summary>
        internal static string DispChecked {
            get {
                return ResourceManager.GetString("DispChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列数 的本地化字符串。
        /// </summary>
        internal static string DispColumnCount {
            get {
                return ResourceManager.GetString("DispColumnCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列名 的本地化字符串。
        /// </summary>
        internal static string DispColumnName {
            get {
                return ResourceManager.GetString("DispColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置列集合 的本地化字符串。
        /// </summary>
        internal static string DispColumns {
            get {
                return ResourceManager.GetString("DispColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列样式 的本地化字符串。
        /// </summary>
        internal static string DispColumnStyles {
            get {
                return ResourceManager.GetString("DispColumnStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对应的列名 的本地化字符串。
        /// </summary>
        internal static string DispDataPropertyName {
            get {
                return ResourceManager.GetString("DispDataPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据属性 的本地化字符串。
        /// </summary>
        internal static string DispDataSourceProperties {
            get {
                return ResourceManager.GetString("DispDataSourceProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控件事件 的本地化字符串。
        /// </summary>
        internal static string DispEventType {
            get {
                return ResourceManager.GetString("DispEventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字段类型 的本地化字符串。
        /// </summary>
        internal static string DispFiledType {
            get {
                return ResourceManager.GetString("DispFiledType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字体 的本地化字符串。
        /// </summary>
        internal static string DispFont {
            get {
                return ResourceManager.GetString("DispFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 颜色 的本地化字符串。
        /// </summary>
        internal static string DispForeColor {
            get {
                return ResourceManager.GetString("DispForeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络行颜色 的本地化字符串。
        /// </summary>
        internal static string DispGridColor {
            get {
                return ResourceManager.GetString("DispGridColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列头显示名称  的本地化字符串。
        /// </summary>
        internal static string DispHeaderText {
            get {
                return ResourceManager.GetString("DispHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐藏字段 的本地化字符串。
        /// </summary>
        internal static string DispHideFileds {
            get {
                return ResourceManager.GetString("DispHideFileds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 树节点显示的成员 的本地化字符串。
        /// </summary>
        internal static string DisplayMember {
            get {
                return ResourceManager.GetString("DisplayMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 长度 的本地化字符串。
        /// </summary>
        internal static string DispLength {
            get {
                return ResourceManager.GetString("DispLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 父成员 的本地化字符串。
        /// </summary>
        internal static string DispParentMember {
            get {
                return ResourceManager.GetString("DispParentMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只读 的本地化字符串。
        /// </summary>
        internal static string DispReadOnly {
            get {
                return ResourceManager.GetString("DispReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行数 的本地化字符串。
        /// </summary>
        internal static string DispRowCount {
            get {
                return ResourceManager.GetString("DispRowCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行样式 的本地化字符串。
        /// </summary>
        internal static string DispRowStyles {
            get {
                return ResourceManager.GetString("DispRowStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 滚动条 的本地化字符串。
        /// </summary>
        internal static string DispScrollBars {
            get {
                return ResourceManager.GetString("DispScrollBars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大小 的本地化字符串。
        /// </summary>
        internal static string DispSize {
            get {
                return ResourceManager.GetString("DispSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tab顺序 的本地化字符串。
        /// </summary>
        internal static string DispTabIndex {
            get {
                return ResourceManager.GetString("DispTabIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目标控件 的本地化字符串。
        /// </summary>
        internal static string DispTargetControlName {
            get {
                return ResourceManager.GetString("DispTargetControlName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目标控件属性 的本地化字符串。
        /// </summary>
        internal static string DispTargetControlProperty {
            get {
                return ResourceManager.GetString("DispTargetControlProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本 的本地化字符串。
        /// </summary>
        internal static string DispText {
            get {
                return ResourceManager.GetString("DispText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据值 的本地化字符串。
        /// </summary>
        internal static string DispValue {
            get {
                return ResourceManager.GetString("DispValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 布局 的本地化字符串。
        /// </summary>
        internal static string Dock {
            get {
                return ResourceManager.GetString("Dock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 职位调动类型数据源 的本地化字符串。
        /// </summary>
        internal static string DutyChangeBindingSourceDesc {
            get {
                return ResourceManager.GetString("DutyChangeBindingSourceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 职位调动 的本地化字符串。
        /// </summary>
        internal static string DutyChangeBindingSourceTitle {
            get {
                return ResourceManager.GetString("DutyChangeBindingSourceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 英文显示成员 的本地化字符串。
        /// </summary>
        internal static string EDisplayMember {
            get {
                return ResourceManager.GetString("EDisplayMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值 的本地化字符串。
        /// </summary>
        internal static string EditValue {
            get {
                return ResourceManager.GetString("EditValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 英文显示成员 的本地化字符串。
        /// </summary>
        internal static string EFullDisplayMember {
            get {
                return ResourceManager.GetString("EFullDisplayMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 英文环境时,呈现的标题. 的本地化字符串。
        /// </summary>
        internal static string EnglishDescription {
            get {
                return ResourceManager.GetString("EnglishDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误列表: 的本地化字符串。
        /// </summary>
        internal static string Errors {
            get {
                return ResourceManager.GetString("Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 英文标题 的本地化字符串。
        /// </summary>
        internal static string EText {
            get {
                return ResourceManager.GetString("EText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}]英文标题存在重复[{1}] 的本地化字符串。
        /// </summary>
        internal static string ETextRepeat {
            get {
                return ResourceManager.GetString("ETextRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事件 的本地化字符串。
        /// </summary>
        internal static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 的本地化字符串。
        /// </summary>
        internal static string EventType {
            get {
                return ResourceManager.GetString("EventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控件对应的字段类型 的本地化字符串。
        /// </summary>
        internal static string FiledType {
            get {
                return ResourceManager.GetString("FiledType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索文本框 的本地化字符串。
        /// </summary>
        internal static string FindTextBox {
            get {
                return ResourceManager.GetString("FindTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 带搜索器的文本框 的本地化字符串。
        /// </summary>
        internal static string FindTextBoxDesc {
            get {
                return ResourceManager.GetString("FindTextBoxDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示成员 的本地化字符串。
        /// </summary>
        internal static string FindTextDisplayMember {
            get {
                return ResourceManager.GetString("FindTextDisplayMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索类型(Customer-&gt;客户,User-&gt;用户) 的本地化字符串。
        /// </summary>
        internal static string FindTextFindTypeDesc {
            get {
                return ResourceManager.GetString("FindTextFindTypeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索类型 的本地化字符串。
        /// </summary>
        internal static string FindTextFindTypeSC {
            get {
                return ResourceManager.GetString("FindTextFindTypeSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索类型 的本地化字符串。
        /// </summary>
        internal static string FindTextFindTypeSD {
            get {
                return ResourceManager.GetString("FindTextFindTypeSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索类型 的本地化字符串。
        /// </summary>
        internal static string FindTextSearchMember {
            get {
                return ResourceManager.GetString("FindTextSearchMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值成员 的本地化字符串。
        /// </summary>
        internal static string FindTextValueMember {
            get {
                return ResourceManager.GetString("FindTextValueMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索类型 的本地化字符串。
        /// </summary>
        internal static string FindType {
            get {
                return ResourceManager.GetString("FindType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控件字体 的本地化字符串。
        /// </summary>
        internal static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控件的字体颜色 的本地化字符串。
        /// </summary>
        internal static string ForeColor {
            get {
                return ResourceManager.GetString("ForeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表单[{0}]没有任何列 的本地化字符串。
        /// </summary>
        internal static string FormNotColumn {
            get {
                return ResourceManager.GetString("FormNotColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本显示成员 的本地化字符串。
        /// </summary>
        internal static string FullDisplayMember {
            get {
                return ResourceManager.GetString("FullDisplayMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络行颜色 的本地化字符串。
        /// </summary>
        internal static string GridColor {
            get {
                return ResourceManager.GetString("GridColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列头 的本地化字符串。
        /// </summary>
        internal static string HeaderText {
            get {
                return ResourceManager.GetString("HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 附件控件 的本地化字符串。
        /// </summary>
        internal static string ICPFilePanelDesc {
            get {
                return ResourceManager.GetString("ICPFilePanelDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 附件控件 的本地化字符串。
        /// </summary>
        internal static string ICPFilePanelTitle {
            get {
                return ResourceManager.GetString("ICPFilePanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项集合 的本地化字符串。
        /// </summary>
        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 职位数据 的本地化字符串。
        /// </summary>
        internal static string JobBindingSourceDesc {
            get {
                return ResourceManager.GetString("JobBindingSourceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 职位 的本地化字符串。
        /// </summary>
        internal static string JobBindingSourceTitle {
            get {
                return ResourceManager.GetString("JobBindingSourceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签 的本地化字符串。
        /// </summary>
        internal static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通常用于提供控件的描述性文字 的本地化字符串。
        /// </summary>
        internal static string LableDesc {
            get {
                return ResourceManager.GetString("LableDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签 的本地化字符串。
        /// </summary>
        internal static string LableTitle {
            get {
                return ResourceManager.GetString("LableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 布局 的本地化字符串。
        /// </summary>
        internal static string Layout {
            get {
                return ResourceManager.GetString("Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CRM客户 的本地化字符串。
        /// </summary>
        internal static string LWFindICPCRM {
            get {
                return ResourceManager.GetString("LWFindICPCRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 业务号 的本地化字符串。
        /// </summary>
        internal static string LWFindOperationNo {
            get {
                return ResourceManager.GetString("LWFindOperationNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分隔符 的本地化字符串。
        /// </summary>
        internal static string LWSplitterDesc {
            get {
                return ResourceManager.GetString("LWSplitterDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分隔符 的本地化字符串。
        /// </summary>
        internal static string LWSplitterTitle {
            get {
                return ResourceManager.GetString("LWSplitterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 如果是文本.则限制最大输入长度. 的本地化字符串。
        /// </summary>
        internal static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择多行 的本地化字符串。
        /// </summary>
        internal static string MultiSelect {
            get {
                return ResourceManager.GetString("MultiSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可以跨越多行的文本框 的本地化字符串。
        /// </summary>
        internal static string MultiTextBoxDesc {
            get {
                return ResourceManager.GetString("MultiTextBoxDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多行文本框 的本地化字符串。
        /// </summary>
        internal static string MultiTextBoxTitel {
            get {
                return ResourceManager.GetString("MultiTextBoxTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须填写 的本地化字符串。
        /// </summary>
        internal static string MustInput {
            get {
                return ResourceManager.GetString("MustInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表单名称 的本地化字符串。
        /// </summary>
        internal static string Nameofform {
            get {
                return ResourceManager.GetString("Nameofform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}]必须设置[{1}]属性. 的本地化字符串。
        /// </summary>
        internal static string NecessaryToProperty {
            get {
                return ResourceManager.GetString("NecessaryToProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持的数据源,数据源必须是DataTable,DataSet,DataView中的一种 的本地化字符串。
        /// </summary>
        internal static string NotSupportedDataSource {
            get {
                return ResourceManager.GetString("NotSupportedDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数字框 的本地化字符串。
        /// </summary>
        internal static string NumericCalcEdit {
            get {
                return ResourceManager.GetString("NumericCalcEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 带计算器的数字控件 的本地化字符串。
        /// </summary>
        internal static string NumericCalcEditDesc {
            get {
                return ResourceManager.GetString("NumericCalcEditDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数字框 的本地化字符串。
        /// </summary>
        internal static string NumericCalcEditTitle {
            get {
                return ResourceManager.GetString("NumericCalcEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数字类型 的本地化字符串。
        /// </summary>
        internal static string NumericType {
            get {
                return ResourceManager.GetString("NumericType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 面板控件 的本地化字符串。
        /// </summary>
        internal static string PanelDesc {
            get {
                return ResourceManager.GetString("PanelDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 面板 的本地化字符串。
        /// </summary>
        internal static string PanelTitle {
            get {
                return ResourceManager.GetString("PanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置父成员(控件以此建立树结构) 的本地化字符串。
        /// </summary>
        internal static string ParentMember {
            get {
                return ResourceManager.GetString("ParentMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先设置数据源 的本地化字符串。
        /// </summary>
        internal static string Pleasesetthedatasource {
            get {
                return ResourceManager.GetString("Pleasesetthedatasource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 岗位 的本地化字符串。
        /// </summary>
        internal static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报销类型数据库源 的本地化字符串。
        /// </summary>
        internal static string PropertyBindingSourceDesc {
            get {
                return ResourceManager.GetString("PropertyBindingSourceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报销类型 的本地化字符串。
        /// </summary>
        internal static string PropertyBindingSourceTitle {
            get {
                return ResourceManager.GetString("PropertyBindingSourceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单选 的本地化字符串。
        /// </summary>
        internal static string Radio {
            get {
                return ResourceManager.GetString("Radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单选按钮 的本地化字符串。
        /// </summary>
        internal static string RadioButton {
            get {
                return ResourceManager.GetString("RadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单选按钮面板 的本地化字符串。
        /// </summary>
        internal static string RadioGroup {
            get {
                return ResourceManager.GetString("RadioGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只读 的本地化字符串。
        /// </summary>
        internal static string ReadOnly {
            get {
                return ResourceManager.GetString("ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置控件是否只读 的本地化字符串。
        /// </summary>
        internal static string ReadOnlyDesc {
            get {
                return ResourceManager.GetString("ReadOnlyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 跨行 的本地化字符串。
        /// </summary>
        internal static string RowSpan {
            get {
                return ResourceManager.GetString("RowSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询 的本地化字符串。
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索类型(Customer-&gt;客户,User-&gt;用户) 的本地化字符串。
        /// </summary>
        internal static string SearchMember {
            get {
                return ResourceManager.GetString("SearchMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择按钮对应的文本 的本地化字符串。
        /// </summary>
        internal static string SelectedText {
            get {
                return ResourceManager.GetString("SelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字体 的本地化字符串。
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 源属性 的本地化字符串。
        /// </summary>
        internal static string SourceProperty {
            get {
                return ResourceManager.GetString("SourceProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 样式 的本地化字符串。
        /// </summary>
        internal static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 布局 的本地化字符串。
        /// </summary>
        internal static string TableLayoutPanelDesc {
            get {
                return ResourceManager.GetString("TableLayoutPanelDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 布局 的本地化字符串。
        /// </summary>
        internal static string TableLayoutPanelTitle {
            get {
                return ResourceManager.GetString("TableLayoutPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义数据 的本地化字符串。
        /// </summary>
        internal static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目标控件的名称 的本地化字符串。
        /// </summary>
        internal static string TargetsControlName {
            get {
                return ResourceManager.GetString("TargetsControlName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目标控件的属性 的本地化字符串。
        /// </summary>
        internal static string TargetsControlProperty {
            get {
                return ResourceManager.GetString("TargetsControlProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本框 的本地化字符串。
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本框 的本地化字符串。
        /// </summary>
        internal static string TextBox {
            get {
                return ResourceManager.GetString("TextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关联的表单名 的本地化字符串。
        /// </summary>
        internal static string Theformofassociation {
            get {
                return ResourceManager.GetString("Theformofassociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不存在数据 的本地化字符串。
        /// </summary>
        internal static string Thereisnodata {
            get {
                return ResourceManager.GetString("Thereisnodata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户 的本地化字符串。
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户数据 的本地化字符串。
        /// </summary>
        internal static string UserBindingSource {
            get {
                return ResourceManager.GetString("UserBindingSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All-&gt;整个鹏城海的用户,Company-&gt;当前用户所在整个公司的用户,Department-&gt;当前用户所在部门的所有用户 的本地化字符串。
        /// </summary>
        internal static string UserBindingSourceDesc {
            get {
                return ResourceManager.GetString("UserBindingSourceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户 的本地化字符串。
        /// </summary>
        internal static string UserBindingSourceTitle {
            get {
                return ResourceManager.GetString("UserBindingSourceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值成员 的本地化字符串。
        /// </summary>
        internal static string ValueMember {
            get {
                return ResourceManager.GetString("ValueMember", resourceCulture);
            }
        }
    }
}
