//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICP.WF.Controls.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceEn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceEn() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ICP.WF.Controls.Resources.ResourceEn", typeof(ResourceEn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Allow Null 的本地化字符串。
        /// </summary>
        internal static string AllowNull {
            get {
                return ResourceManager.GetString("AllowNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AddRows 的本地化字符串。
        /// </summary>
        internal static string AllowUserToAddRows {
            get {
                return ResourceManager.GetString("AllowUserToAddRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeleteRow 的本地化字符串。
        /// </summary>
        internal static string AllowUserToDeleteRows {
            get {
                return ResourceManager.GetString("AllowUserToDeleteRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OrderColumns 的本地化字符串。
        /// </summary>
        internal static string AllowUserToOrderColumns {
            get {
                return ResourceManager.GetString("AllowUserToOrderColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Anchor 的本地化字符串。
        /// </summary>
        internal static string Anchor {
            get {
                return ResourceManager.GetString("Anchor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Generator No 的本地化字符串。
        /// </summary>
        internal static string AutoGeneratorNumber {
            get {
                return ResourceManager.GetString("AutoGeneratorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Base 的本地化字符串。
        /// </summary>
        internal static string Base {
            get {
                return ResourceManager.GetString("Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bold 的本地化字符串。
        /// </summary>
        internal static string Bold {
            get {
                return ResourceManager.GetString("Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese Display Member 的本地化字符串。
        /// </summary>
        internal static string CDisplayMember {
            get {
                return ResourceManager.GetString("CDisplayMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese Full Display Member 的本地化字符串。
        /// </summary>
        internal static string CFullDisplayMember {
            get {
                return ResourceManager.GetString("CFullDisplayMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CheckBox 的本地化字符串。
        /// </summary>
        internal static string CheckBox {
            get {
                return ResourceManager.GetString("CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use a CheckBox to give the user an option, such as true/false or yes/no 的本地化字符串。
        /// </summary>
        internal static string CheckBoxDesc {
            get {
                return ResourceManager.GetString("CheckBoxDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CheckBox 的本地化字符串。
        /// </summary>
        internal static string CheckBoxTitle {
            get {
                return ResourceManager.GetString("CheckBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese environment, the show&apos;s title 的本地化字符串。
        /// </summary>
        internal static string ChineseDescription {
            get {
                return ResourceManager.GetString("ChineseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Column Name 的本地化字符串。
        /// </summary>
        internal static string ColumnName {
            get {
                return ResourceManager.GetString("ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{ 0 }]ColumnName Repeat [{ 1 }] 的本地化字符串。
        /// </summary>
        internal static string ColumnNameRepeat {
            get {
                return ResourceManager.GetString("ColumnNameRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Column Span 的本地化字符串。
        /// </summary>
        internal static string ColumnSpan {
            get {
                return ResourceManager.GetString("ColumnSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ColumnsWidth 的本地化字符串。
        /// </summary>
        internal static string ColumnsWidth {
            get {
                return ResourceManager.GetString("ColumnsWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ComboBox 的本地化字符串。
        /// </summary>
        internal static string ComboBox {
            get {
                return ResourceManager.GetString("ComboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ComboBox TreeView 的本地化字符串。
        /// </summary>
        internal static string ComboBoxTreeViewDesc {
            get {
                return ResourceManager.GetString("ComboBoxTreeViewDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Provide a list of users select from a 的本地化字符串。
        /// </summary>
        internal static string ComBoxDesc {
            get {
                return ResourceManager.GetString("ComBoxDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ComBox 的本地化字符串。
        /// </summary>
        internal static string ComBoxTitle {
            get {
                return ResourceManager.GetString("ComBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Company 的本地化字符串。
        /// </summary>
        internal static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Companys 的本地化字符串。
        /// </summary>
        internal static string CompanyBindingSource {
            get {
                return ResourceManager.GetString("CompanyBindingSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Company Data 的本地化字符串。
        /// </summary>
        internal static string CompanyBindingSourceDesc {
            get {
                return ResourceManager.GetString("CompanyBindingSourceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Company Data 的本地化字符串。
        /// </summary>
        internal static string CompanyBindingSourceTitle {
            get {
                return ResourceManager.GetString("CompanyBindingSourceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All-&gt;All Company,Company-&gt;Current users of the company,Department-&gt;Current users of the departments 的本地化字符串。
        /// </summary>
        internal static string CompanySourceTypeDescription {
            get {
                return ResourceManager.GetString("CompanySourceTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The control data sources inside the properties 的本地化字符串。
        /// </summary>
        internal static string ControlDataSourceProperties {
            get {
                return ResourceManager.GetString("ControlDataSourceProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Control event 的本地化字符串。
        /// </summary>
        internal static string Controlevent {
            get {
                return ResourceManager.GetString("Controlevent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Control Property 的本地化字符串。
        /// </summary>
        internal static string ControlProperty {
            get {
                return ResourceManager.GetString("ControlProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CText 的本地化字符串。
        /// </summary>
        internal static string CText {
            get {
                return ResourceManager.GetString("CText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}]CText Property[{1}] repeat 的本地化字符串。
        /// </summary>
        internal static string CTextRepeat {
            get {
                return ResourceManager.GetString("CTextRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Currency 的本地化字符串。
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Currencies 的本地化字符串。
        /// </summary>
        internal static string CurrencyBindingSource {
            get {
                return ResourceManager.GetString("CurrencyBindingSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Currencies 的本地化字符串。
        /// </summary>
        internal static string CurrencyBindingSourceTitle {
            get {
                return ResourceManager.GetString("CurrencyBindingSourceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom 的本地化字符串。
        /// </summary>
        internal static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data 的本地化字符串。
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Binding 的本地化字符串。
        /// </summary>
        internal static string DataBinding {
            get {
                return ResourceManager.GetString("DataBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Custom 的本地化字符串。
        /// </summary>
        internal static string DataCustom {
            get {
                return ResourceManager.GetString("DataCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Dictionaries Source 的本地化字符串。
        /// </summary>
        internal static string DataDictionariesSourceDesc {
            get {
                return ResourceManager.GetString("DataDictionariesSourceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Dictionaries 的本地化字符串。
        /// </summary>
        internal static string DataDictionariesSourceTitle {
            get {
                return ResourceManager.GetString("DataDictionariesSourceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Dictionary Type 的本地化字符串。
        /// </summary>
        internal static string DataDictionaryTypeDescription {
            get {
                return ResourceManager.GetString("DataDictionaryTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DataGridView 的本地化字符串。
        /// </summary>
        internal static string DataGridView {
            get {
                return ResourceManager.GetString("DataGridView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Provides a customizable table for displaying data 的本地化字符串。
        /// </summary>
        internal static string DataGridViewDesc {
            get {
                return ResourceManager.GetString("DataGridViewDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DataGridView 的本地化字符串。
        /// </summary>
        internal static string DataGridViewTitle {
            get {
                return ResourceManager.GetString("DataGridViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Property 的本地化字符串。
        /// </summary>
        internal static string DataProperty {
            get {
                return ResourceManager.GetString("DataProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Scope 的本地化字符串。
        /// </summary>
        internal static string DataScope {
            get {
                return ResourceManager.GetString("DataScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Source 的本地化字符串。
        /// </summary>
        internal static string DataSource {
            get {
                return ResourceManager.GetString("DataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date 的本地化字符串。
        /// </summary>
        internal static string DatePicker {
            get {
                return ResourceManager.GetString("DatePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The DateTimePicker control is used to allow the user to select a date and time, and to display that date and time in the specified forma 的本地化字符串。
        /// </summary>
        internal static string DatePickerDesc {
            get {
                return ResourceManager.GetString("DatePickerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DatePicker 的本地化字符串。
        /// </summary>
        internal static string DatePickerTitle {
            get {
                return ResourceManager.GetString("DatePickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default Value 的本地化字符串。
        /// </summary>
        internal static string DefaultValue {
            get {
                return ResourceManager.GetString("DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Degree 的本地化字符串。
        /// </summary>
        internal static string DegreeBindingSourceDesc {
            get {
                return ResourceManager.GetString("DegreeBindingSourceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Degree 的本地化字符串。
        /// </summary>
        internal static string DegreeBindingSourceTitle {
            get {
                return ResourceManager.GetString("DegreeBindingSourceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ColumnsWidth 的本地化字符串。
        /// </summary>
        internal static string DescColumnsWidth {
            get {
                return ResourceManager.GetString("DescColumnsWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set Control is Readonly 的本地化字符串。
        /// </summary>
        internal static string DescReadOnly {
            get {
                return ResourceManager.GetString("DescReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ScrollBars 的本地化字符串。
        /// </summary>
        internal static string DescScrollBars {
            get {
                return ResourceManager.GetString("DescScrollBars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size 的本地化字符串。
        /// </summary>
        internal static string DescSize {
            get {
                return ResourceManager.GetString("DescSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AllowNull 的本地化字符串。
        /// </summary>
        internal static string DispAllowNull {
            get {
                return ResourceManager.GetString("DispAllowNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set Control BackColor 的本地化字符串。
        /// </summary>
        internal static string DispBackColor {
            get {
                return ResourceManager.GetString("DispBackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set Columns 的本地化字符串。
        /// </summary>
        internal static string DispColumns {
            get {
                return ResourceManager.GetString("DispColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DataPropertyName 的本地化字符串。
        /// </summary>
        internal static string DispDataPropertyName {
            get {
                return ResourceManager.GetString("DispDataPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DataSourceProperties 的本地化字符串。
        /// </summary>
        internal static string DispDataSourceProperties {
            get {
                return ResourceManager.GetString("DispDataSourceProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DispEventType 的本地化字符串。
        /// </summary>
        internal static string DispEventType {
            get {
                return ResourceManager.GetString("DispEventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FiledType 的本地化字符串。
        /// </summary>
        internal static string DispFiledType {
            get {
                return ResourceManager.GetString("DispFiledType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color 的本地化字符串。
        /// </summary>
        internal static string DispForeColor {
            get {
                return ResourceManager.GetString("DispForeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GridColor 的本地化字符串。
        /// </summary>
        internal static string DispGridColor {
            get {
                return ResourceManager.GetString("DispGridColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HeaderText 的本地化字符串。
        /// </summary>
        internal static string DispHeaderText {
            get {
                return ResourceManager.GetString("DispHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HideFileds 的本地化字符串。
        /// </summary>
        internal static string DispHideFileds {
            get {
                return ResourceManager.GetString("DispHideFileds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display Member 的本地化字符串。
        /// </summary>
        internal static string DisplayMember {
            get {
                return ResourceManager.GetString("DisplayMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Length 的本地化字符串。
        /// </summary>
        internal static string DispLength {
            get {
                return ResourceManager.GetString("DispLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReadOnly 的本地化字符串。
        /// </summary>
        internal static string DispReadOnly {
            get {
                return ResourceManager.GetString("DispReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ScrollBars 的本地化字符串。
        /// </summary>
        internal static string DispScrollBars {
            get {
                return ResourceManager.GetString("DispScrollBars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size 的本地化字符串。
        /// </summary>
        internal static string DispSize {
            get {
                return ResourceManager.GetString("DispSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DispTabIndex 的本地化字符串。
        /// </summary>
        internal static string DispTabIndex {
            get {
                return ResourceManager.GetString("DispTabIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TargetControlName 的本地化字符串。
        /// </summary>
        internal static string DispTargetControlName {
            get {
                return ResourceManager.GetString("DispTargetControlName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TargetControlProperty 的本地化字符串。
        /// </summary>
        internal static string DispTargetControlProperty {
            get {
                return ResourceManager.GetString("DispTargetControlProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text 的本地化字符串。
        /// </summary>
        internal static string DispText {
            get {
                return ResourceManager.GetString("DispText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value 的本地化字符串。
        /// </summary>
        internal static string DispValue {
            get {
                return ResourceManager.GetString("DispValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dock 的本地化字符串。
        /// </summary>
        internal static string Dock {
            get {
                return ResourceManager.GetString("Dock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DutyChange BindingSource 的本地化字符串。
        /// </summary>
        internal static string DutyChangeBindingSourceDesc {
            get {
                return ResourceManager.GetString("DutyChangeBindingSourceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DutyChange 的本地化字符串。
        /// </summary>
        internal static string DutyChangeBindingSourceTitle {
            get {
                return ResourceManager.GetString("DutyChangeBindingSourceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English Display Member 的本地化字符串。
        /// </summary>
        internal static string EDisplayMember {
            get {
                return ResourceManager.GetString("EDisplayMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EditValue 的本地化字符串。
        /// </summary>
        internal static string EditValue {
            get {
                return ResourceManager.GetString("EditValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English Full Display Member 的本地化字符串。
        /// </summary>
        internal static string EFullDisplayMember {
            get {
                return ResourceManager.GetString("EFullDisplayMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English environment, the show&apos;s title 的本地化字符串。
        /// </summary>
        internal static string EnglishDescription {
            get {
                return ResourceManager.GetString("EnglishDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Errors 的本地化字符串。
        /// </summary>
        internal static string Errors {
            get {
                return ResourceManager.GetString("Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EText 的本地化字符串。
        /// </summary>
        internal static string EText {
            get {
                return ResourceManager.GetString("EText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}]EText Property[{1}] repeat 的本地化字符串。
        /// </summary>
        internal static string ETextRepeat {
            get {
                return ResourceManager.GetString("ETextRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Event 的本地化字符串。
        /// </summary>
        internal static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        internal static string EventType {
            get {
                return ResourceManager.GetString("EventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find TextBox 的本地化字符串。
        /// </summary>
        internal static string FindTextBox {
            get {
                return ResourceManager.GetString("FindTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find TextBox 的本地化字符串。
        /// </summary>
        internal static string FindTextBoxDesc {
            get {
                return ResourceManager.GetString("FindTextBoxDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DisplayMember 的本地化字符串。
        /// </summary>
        internal static string FindTextDisplayMember {
            get {
                return ResourceManager.GetString("FindTextDisplayMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FindType 的本地化字符串。
        /// </summary>
        internal static string FindTextFindTypeDesc {
            get {
                return ResourceManager.GetString("FindTextFindTypeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FindType 的本地化字符串。
        /// </summary>
        internal static string FindTextFindTypeSC {
            get {
                return ResourceManager.GetString("FindTextFindTypeSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FindType 的本地化字符串。
        /// </summary>
        internal static string FindTextFindTypeSD {
            get {
                return ResourceManager.GetString("FindTextFindTypeSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SearchMember 的本地化字符串。
        /// </summary>
        internal static string FindTextSearchMember {
            get {
                return ResourceManager.GetString("FindTextSearchMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ValueMember 的本地化字符串。
        /// </summary>
        internal static string FindTextValueMember {
            get {
                return ResourceManager.GetString("FindTextValueMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find Type 的本地化字符串。
        /// </summary>
        internal static string FindType {
            get {
                return ResourceManager.GetString("FindType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font 的本地化字符串。
        /// </summary>
        internal static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ForeColor 的本地化字符串。
        /// </summary>
        internal static string ForeColor {
            get {
                return ResourceManager.GetString("ForeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Form [{0}] Not Colum 的本地化字符串。
        /// </summary>
        internal static string FormNotColumn {
            get {
                return ResourceManager.GetString("FormNotColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Full Display Member 的本地化字符串。
        /// </summary>
        internal static string FullDisplayMember {
            get {
                return ResourceManager.GetString("FullDisplayMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HeaderText 的本地化字符串。
        /// </summary>
        internal static string HeaderText {
            get {
                return ResourceManager.GetString("HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Panel 的本地化字符串。
        /// </summary>
        internal static string ICPFilePanelDesc {
            get {
                return ResourceManager.GetString("ICPFilePanelDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Panel 的本地化字符串。
        /// </summary>
        internal static string ICPFilePanelTitle {
            get {
                return ResourceManager.GetString("ICPFilePanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Items 的本地化字符串。
        /// </summary>
        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Job 的本地化字符串。
        /// </summary>
        internal static string JobBindingSourceDesc {
            get {
                return ResourceManager.GetString("JobBindingSourceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Job Data 的本地化字符串。
        /// </summary>
        internal static string JobBindingSourceTitle {
            get {
                return ResourceManager.GetString("JobBindingSourceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Label 的本地化字符串。
        /// </summary>
        internal static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are typically used to provide descriptive text for a control. For example 的本地化字符串。
        /// </summary>
        internal static string LableDesc {
            get {
                return ResourceManager.GetString("LableDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lable 的本地化字符串。
        /// </summary>
        internal static string LableTitle {
            get {
                return ResourceManager.GetString("LableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Layout 的本地化字符串。
        /// </summary>
        internal static string Layout {
            get {
                return ResourceManager.GetString("Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CRM Find 的本地化字符串。
        /// </summary>
        internal static string LWFindICPCRM {
            get {
                return ResourceManager.GetString("LWFindICPCRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OperationNo Find 的本地化字符串。
        /// </summary>
        internal static string LWFindOperationNo {
            get {
                return ResourceManager.GetString("LWFindOperationNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max Length 的本地化字符串。
        /// </summary>
        internal static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MultiSelect 的本地化字符串。
        /// </summary>
        internal static string MultiSelect {
            get {
                return ResourceManager.GetString("MultiSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multi TextBox 的本地化字符串。
        /// </summary>
        internal static string MultiTextBoxDesc {
            get {
                return ResourceManager.GetString("MultiTextBoxDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MultiTextBox 的本地化字符串。
        /// </summary>
        internal static string MultiTextBoxTitel {
            get {
                return ResourceManager.GetString("MultiTextBoxTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Must Input 的本地化字符串。
        /// </summary>
        internal static string MustInput {
            get {
                return ResourceManager.GetString("MustInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name of form 的本地化字符串。
        /// </summary>
        internal static string Nameofform {
            get {
                return ResourceManager.GetString("Nameofform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}]Necessary to set up [{1}] property 的本地化字符串。
        /// </summary>
        internal static string NecessaryToProperty {
            get {
                return ResourceManager.GetString("NecessaryToProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not supported by data sources, data sources must be DataTable, DataSet, DataView 的本地化字符串。
        /// </summary>
        internal static string NotSupportedDataSource {
            get {
                return ResourceManager.GetString("NotSupportedDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Numeric 的本地化字符串。
        /// </summary>
        internal static string NumericCalcEdit {
            get {
                return ResourceManager.GetString("NumericCalcEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Digital controls with Calculator 的本地化字符串。
        /// </summary>
        internal static string NumericCalcEditDesc {
            get {
                return ResourceManager.GetString("NumericCalcEditDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NumericCalcEdit 的本地化字符串。
        /// </summary>
        internal static string NumericCalcEditTitle {
            get {
                return ResourceManager.GetString("NumericCalcEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Numeric Type 的本地化字符串。
        /// </summary>
        internal static string NumericType {
            get {
                return ResourceManager.GetString("NumericType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Panel 的本地化字符串。
        /// </summary>
        internal static string PanelDesc {
            get {
                return ResourceManager.GetString("PanelDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Panel 的本地化字符串。
        /// </summary>
        internal static string PanelTitle {
            get {
                return ResourceManager.GetString("PanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parent Member 的本地化字符串。
        /// </summary>
        internal static string ParentMember {
            get {
                return ResourceManager.GetString("ParentMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please set the data source 的本地化字符串。
        /// </summary>
        internal static string Pleasesetthedatasource {
            get {
                return ResourceManager.GetString("Pleasesetthedatasource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Post 的本地化字符串。
        /// </summary>
        internal static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PropertyBindingSource 的本地化字符串。
        /// </summary>
        internal static string PropertyBindingSourceDesc {
            get {
                return ResourceManager.GetString("PropertyBindingSourceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Property 的本地化字符串。
        /// </summary>
        internal static string PropertyBindingSourceTitle {
            get {
                return ResourceManager.GetString("PropertyBindingSourceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RadioGroup 的本地化字符串。
        /// </summary>
        internal static string Radio {
            get {
                return ResourceManager.GetString("Radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RadioButton 的本地化字符串。
        /// </summary>
        internal static string RadioButton {
            get {
                return ResourceManager.GetString("RadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Radio Group 的本地化字符串。
        /// </summary>
        internal static string RadioGroup {
            get {
                return ResourceManager.GetString("RadioGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ReadOnly 的本地化字符串。
        /// </summary>
        internal static string ReadOnly {
            get {
                return ResourceManager.GetString("ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set Control Is ReadOnly 的本地化字符串。
        /// </summary>
        internal static string ReadOnlyDesc {
            get {
                return ResourceManager.GetString("ReadOnlyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Row Span 的本地化字符串。
        /// </summary>
        internal static string RowSpan {
            get {
                return ResourceManager.GetString("RowSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search Member 的本地化字符串。
        /// </summary>
        internal static string SearchMember {
            get {
                return ResourceManager.GetString("SearchMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selected Text 的本地化字符串。
        /// </summary>
        internal static string SelectedText {
            get {
                return ResourceManager.GetString("SelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size 的本地化字符串。
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SourceProperty 的本地化字符串。
        /// </summary>
        internal static string SourceProperty {
            get {
                return ResourceManager.GetString("SourceProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Style 的本地化字符串。
        /// </summary>
        internal static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tag 的本地化字符串。
        /// </summary>
        internal static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The name of target control  的本地化字符串。
        /// </summary>
        internal static string TargetsControlName {
            get {
                return ResourceManager.GetString("TargetsControlName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The property of target control 的本地化字符串。
        /// </summary>
        internal static string TargetsControlProperty {
            get {
                return ResourceManager.GetString("TargetsControlProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TextBox 的本地化字符串。
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TextBox 的本地化字符串。
        /// </summary>
        internal static string TextBox {
            get {
                return ResourceManager.GetString("TextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The form of association 的本地化字符串。
        /// </summary>
        internal static string Theformofassociation {
            get {
                return ResourceManager.GetString("Theformofassociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is no data 的本地化字符串。
        /// </summary>
        internal static string Thereisnodata {
            get {
                return ResourceManager.GetString("Thereisnodata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User 的本地化字符串。
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Users 的本地化字符串。
        /// </summary>
        internal static string UserBindingSource {
            get {
                return ResourceManager.GetString("UserBindingSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All-&gt;The whole city ocean company,Company-&gt;Current users of the company&apos;s users,Department-&gt;Current users of the departments of all users 的本地化字符串。
        /// </summary>
        internal static string UserSourceTypeDescription {
            get {
                return ResourceManager.GetString("UserSourceTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value Member 的本地化字符串。
        /// </summary>
        internal static string ValueMember {
            get {
                return ResourceManager.GetString("ValueMember", resourceCulture);
            }
        }
    }
}
