//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICP.WF.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_EN() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ICP.WF.UI.Resources.Resource_EN", typeof(Resource_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 No { 0 } has entered the next part of the process, can not cancel 的本地化字符串。
        /// </summary>
        internal static string ApplicationNoCanceledByNextProcess {
            get {
                return ResourceManager.GetString("ApplicationNoCanceledByNextProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No{ 0 } Application not Waiting or Processingstate, can not be canceled 的本地化字符串。
        /// </summary>
        internal static string ApplicationNoCanceledByNoActivated {
            get {
                return ResourceManager.GetString("ApplicationNoCanceledByNoActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No{ 0 } Application process than their own, can not be canceled 的本地化字符串。
        /// </summary>
        internal static string ApplicationNoCanceledByNoMy {
            get {
                return ResourceManager.GetString("ApplicationNoCanceledByNoMy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Srue Cancel WorkFlow? 的本地化字符串。
        /// </summary>
        internal static string CancelWorkFlow {
            get {
                return ResourceManager.GetString("CancelWorkFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t sort 的本地化字符串。
        /// </summary>
        internal static string CantSort {
            get {
                return ResourceManager.GetString("CantSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Srue Delete Current Data? 的本地化字符串。
        /// </summary>
        internal static string DeleteData {
            get {
                return ResourceManager.GetString("DeleteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 failly 的本地化字符串。
        /// </summary>
        internal static string Failly {
            get {
                return ResourceManager.GetString("Failly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Form 的本地化字符串。
        /// </summary>
        internal static string Form {
            get {
                return ResourceManager.GetString("Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Doing Work 的本地化字符串。
        /// </summary>
        internal static string InDoWork {
            get {
                return ResourceManager.GetString("InDoWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Info 的本地化字符串。
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select the personnel to be assigned 的本地化字符串。
        /// </summary>
        internal static string PleaseAssignedPerson {
            get {
                return ResourceManager.GetString("PleaseAssignedPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please choose to receipt of data 的本地化字符串。
        /// </summary>
        internal static string Pleasechoosedata {
            get {
                return ResourceManager.GetString("Pleasechoosedata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select [{0}] executor 的本地化字符串。
        /// </summary>
        internal static string SelectExecutor {
            get {
                return ResourceManager.GetString("SelectExecutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start WorkFlow 的本地化字符串。
        /// </summary>
        internal static string StartWorkFlow {
            get {
                return ResourceManager.GetString("StartWorkFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Successfully 的本地化字符串。
        /// </summary>
        internal static string Successfully {
            get {
                return ResourceManager.GetString("Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View Work 的本地化字符串。
        /// </summary>
        internal static string ViewWork {
            get {
                return ResourceManager.GetString("ViewWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show of work before you sign for the content of the work. 的本地化字符串。
        /// </summary>
        internal static string ViewWorkFirstSign {
            get {
                return ResourceManager.GetString("ViewWorkFirstSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Waiting Work 的本地化字符串。
        /// </summary>
        internal static string WaitingWork {
            get {
                return ResourceManager.GetString("WaitingWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workaround 的本地化字符串。
        /// </summary>
        internal static string Workaround {
            get {
                return ResourceManager.GetString("Workaround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Work List 的本地化字符串。
        /// </summary>
        internal static string WorkList {
            get {
                return ResourceManager.GetString("WorkList", resourceCulture);
            }
        }
    }
}
