//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICP.WF.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_CN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_CN() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ICP.WF.UI.Resources.Resource_CN", typeof(Resource_CN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 单号 {0} 的流程已进入下一个环节，无法取消 的本地化字符串。
        /// </summary>
        internal static string ApplicationNoCanceledByNextProcess {
            get {
                return ResourceManager.GetString("ApplicationNoCanceledByNextProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单号 {0} 的流程不是待办或在办状态，无法取消 的本地化字符串。
        /// </summary>
        internal static string ApplicationNoCanceledByNoActivated {
            get {
                return ResourceManager.GetString("ApplicationNoCanceledByNoActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单号 {0} 的流程不是自己申请的，无法取消 的本地化字符串。
        /// </summary>
        internal static string ApplicationNoCanceledByNoMy {
            get {
                return ResourceManager.GetString("ApplicationNoCanceledByNoMy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否取消本次任务？ 的本地化字符串。
        /// </summary>
        internal static string CancelWorkFlow {
            get {
                return ResourceManager.GetString("CancelWorkFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能排序 的本地化字符串。
        /// </summary>
        internal static string CantSort {
            get {
                return ResourceManager.GetString("CantSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否删除当前数据？ 的本地化字符串。
        /// </summary>
        internal static string DeleteData {
            get {
                return ResourceManager.GetString("DeleteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败 的本地化字符串。
        /// </summary>
        internal static string Failly {
            get {
                return ResourceManager.GetString("Failly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表单 的本地化字符串。
        /// </summary>
        internal static string Form {
            get {
                return ResourceManager.GetString("Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在办工作 的本地化字符串。
        /// </summary>
        internal static string InDoWork {
            get {
                return ResourceManager.GetString("InDoWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息 的本地化字符串。
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择要指派的人员 的本地化字符串。
        /// </summary>
        internal static string PleaseAssignedPerson {
            get {
                return ResourceManager.GetString("PleaseAssignedPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择要签收的数据 的本地化字符串。
        /// </summary>
        internal static string Pleasechoosedata {
            get {
                return ResourceManager.GetString("Pleasechoosedata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择一个[{0}]的执行人. 的本地化字符串。
        /// </summary>
        internal static string SelectExecutor {
            get {
                return ResourceManager.GetString("SelectExecutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发起新流程 的本地化字符串。
        /// </summary>
        internal static string StartWorkFlow {
            get {
                return ResourceManager.GetString("StartWorkFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        internal static string Successfully {
            get {
                return ResourceManager.GetString("Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作查看 的本地化字符串。
        /// </summary>
        internal static string ViewWork {
            get {
                return ResourceManager.GetString("ViewWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看工作内容前请先签收工作项 的本地化字符串。
        /// </summary>
        internal static string ViewWorkFirstSign {
            get {
                return ResourceManager.GetString("ViewWorkFirstSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 待办工作 的本地化字符串。
        /// </summary>
        internal static string WaitingWork {
            get {
                return ResourceManager.GetString("WaitingWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作区 的本地化字符串。
        /// </summary>
        internal static string Workaround {
            get {
                return ResourceManager.GetString("Workaround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作列表 的本地化字符串。
        /// </summary>
        internal static string WorkList {
            get {
                return ResourceManager.GetString("WorkList", resourceCulture);
            }
        }
    }
}
