//
// CSCLBooking.cs
//
// This file was generated by MapForce 2011r2.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the MapForce Documentation for further details.
// http://www.altova.com/mapforce
//


namespace CSCLBooking
{

using Altova.TextParser.Flex;

    public class CSCLBookingDocument : TextDocument 
	{

		// Project Root2
		static private CommandProject command_Root2 = new CommandProject("Root", 0);

		// Switch Sections2
		static private Condition[] conditions_Sections2 = {
			new Condition("", Condition.ConditionType.ContentStartWith, ""),
			new Condition("", Condition.ConditionType.ContentStartWith, ""),
			new Condition("", Condition.ConditionType.ContentStartWith, ""),
			new Condition("", Condition.ConditionType.ContentStartWith, ""),
			new Condition("", Condition.ConditionType.ContentStartWith, ""),
			new Condition("", Condition.ConditionType.ContentStartWith, ""),
			new Condition("", Condition.ConditionType.ContentStartWith, ""),
			new Condition("", Condition.ConditionType.ContentStartWith, ""),
			new Condition("", Condition.ConditionType.ContentStartWith, ""),
			new Condition("", Condition.ConditionType.ContentStartWith, ""),
			new Condition("", Condition.ConditionType.ContentStartWith, ""),
			new Condition("", Condition.ConditionType.ContentStartWith, ""),
			new Condition("", Condition.ConditionType.ContentStartWith, ""),
			new Condition("", Condition.ConditionType.ContentStartWith, ""),
			new Condition("", Condition.ConditionType.ContentStartWith, ""),
			new Condition("", Condition.ConditionType.ContentStartWith, ""),
			new Condition("", Condition.ConditionType.ContentStartWith, ""),
			new Condition("", Condition.ConditionType.ContentStartWith, ""),
		};
		static private CommandSwitch command_Sections2 = new CommandSwitch("Sections", conditions_Sections2, 0);

		// CSV HEAD_RECORD2
		static private CommandStore store_HEAD_RECORD2_RECORD_ID18 = new CommandStore("RECORD ID", 0, "");
		static private CommandStore store_HEAD_RECORD2_SAGE_TYPE2 = new CommandStore("SAGE TYPE", 0, "");
		static private CommandStore store_HEAD_RECORD2_FILE_DESCRIPTION2 = new CommandStore("FILE DESCRIPTION", 0, "");
		static private CommandStore store_HEAD_RECORD2_FILE_FUNCTION2 = new CommandStore("FILE FUNCTION", 0, "");
		static private CommandStore store_HEAD_RECORD2_SENDER_CODE2 = new CommandStore("SENDER CODE", 0, "");
		static private CommandStore store_HEAD_RECORD2_RECEIVER_CODE2 = new CommandStore("RECEIVER CODE", 0, "");
		static private CommandStore store_HEAD_RECORD2_FILE_CREATE_TIME2 = new CommandStore("FILE CREATE TIME", 0, "");
		static private CommandStore store_HEAD_RECORD2_SENDER_PORT_CODE2 = new CommandStore("SENDER PORT CODE", 0, "");
		static private CommandStore store_HEAD_RECORD2_RECEIVER_PORT_CODE2 = new CommandStore("RECEIVER PORT CODE", 0, "");
		static private ColumnDelimited[] columns_HEAD_RECORD2 = {
			new ColumnDelimited(store_HEAD_RECORD2_RECORD_ID18, "RECORD ID"),
			new ColumnDelimited(store_HEAD_RECORD2_SAGE_TYPE2, "SAGE TYPE"),
			new ColumnDelimited(store_HEAD_RECORD2_FILE_DESCRIPTION2, "FILE DESCRIPTION"),
			new ColumnDelimited(store_HEAD_RECORD2_FILE_FUNCTION2, "FILE FUNCTION"),
			new ColumnDelimited(store_HEAD_RECORD2_SENDER_CODE2, "SENDER CODE"),
			new ColumnDelimited(store_HEAD_RECORD2_RECEIVER_CODE2, "RECEIVER CODE"),
			new ColumnDelimited(store_HEAD_RECORD2_FILE_CREATE_TIME2, "FILE CREATE TIME"),
			new ColumnDelimited(store_HEAD_RECORD2_SENDER_PORT_CODE2, "SENDER PORT CODE"),
			new ColumnDelimited(store_HEAD_RECORD2_RECEIVER_PORT_CODE2, "RECEIVER PORT CODE"),
		};
		static private CommandCSV command_HEAD_RECORD2 = new CommandCSV("HEAD RECORD", columns_HEAD_RECORD2, false, "\'\r\n", ":", '\0', '\0', true);

		// CSV VESSEL3
		static private CommandStore store_VESSEL3_RECORD_ID19 = new CommandStore("RECORD ID", 0, "");
		static private CommandStore store_VESSEL3_VESSEL_CODE2 = new CommandStore("VESSEL CODE", 0, "");
		static private CommandStore store_VESSEL3_VESSEL4 = new CommandStore("VESSEL", 0, "");
		static private CommandStore store_VESSEL3_VOYAGE2 = new CommandStore("VOYAGE", 0, "");
		static private CommandStore store_VESSEL3_SHIPPING_LINE_CODE2 = new CommandStore("SHIPPING LINE CODE", 0, "");
		static private CommandStore store_VESSEL3_SHIPPING_LINE2 = new CommandStore("SHIPPING LINE", 0, "");
		static private CommandStore store_VESSEL3_TRADE_CODE2 = new CommandStore("TRADE CODE", 0, "");
		static private CommandStore store_VESSEL3_TRADE2 = new CommandStore("TRADE", 0, "");
		static private CommandStore store_VESSEL3_REQUESTED_SHIPMENT_DATE2 = new CommandStore("REQUESTED SHIPMENT DATE", 0, "");
		static private ColumnDelimited[] columns_VESSEL3 = {
			new ColumnDelimited(store_VESSEL3_RECORD_ID19, "RECORD ID"),
			new ColumnDelimited(store_VESSEL3_VESSEL_CODE2, "VESSEL CODE"),
			new ColumnDelimited(store_VESSEL3_VESSEL4, "VESSEL"),
			new ColumnDelimited(store_VESSEL3_VOYAGE2, "VOYAGE"),
			new ColumnDelimited(store_VESSEL3_SHIPPING_LINE_CODE2, "SHIPPING LINE CODE"),
			new ColumnDelimited(store_VESSEL3_SHIPPING_LINE2, "SHIPPING LINE"),
			new ColumnDelimited(store_VESSEL3_TRADE_CODE2, "TRADE CODE"),
			new ColumnDelimited(store_VESSEL3_TRADE2, "TRADE"),
			new ColumnDelimited(store_VESSEL3_REQUESTED_SHIPMENT_DATE2, "REQUESTED SHIPMENT DATE"),
		};
		static private CommandCSV command_VESSEL3 = new CommandCSV("VESSEL", columns_VESSEL3, false, "\'\r\n", ":", '\0', '\0', true);

		// CSV PRE_VESSEL3
		static private CommandStore store_PRE_VESSEL3_RECORD_ID20 = new CommandStore("RECORD ID", 0, "");
		static private CommandStore store_PRE_VESSEL3_PRE_VESSEL_CODE2 = new CommandStore("PRE.VESSEL CODE", 0, "");
		static private CommandStore store_PRE_VESSEL3_PRE_VESSEL4 = new CommandStore("PRE.VESSEL", 0, "");
		static private CommandStore store_PRE_VESSEL3_PRE_VOYAGE2 = new CommandStore("PRE.VOYAGE", 0, "");
		static private CommandStore store_PRE_VESSEL3_PLACE_OF_RECEIPT_CODE2 = new CommandStore("PLACE OF RECEIPT CODE", 0, "");
		static private CommandStore store_PRE_VESSEL3_PLACE_OF_RECEIPT2 = new CommandStore("PLACE OF RECEIPT", 0, "");
		static private ColumnDelimited[] columns_PRE_VESSEL3 = {
			new ColumnDelimited(store_PRE_VESSEL3_RECORD_ID20, "RECORD ID"),
			new ColumnDelimited(store_PRE_VESSEL3_PRE_VESSEL_CODE2, "PRE.VESSEL CODE"),
			new ColumnDelimited(store_PRE_VESSEL3_PRE_VESSEL4, "PRE.VESSEL"),
			new ColumnDelimited(store_PRE_VESSEL3_PRE_VOYAGE2, "PRE.VOYAGE"),
			new ColumnDelimited(store_PRE_VESSEL3_PLACE_OF_RECEIPT_CODE2, "PLACE OF RECEIPT CODE"),
			new ColumnDelimited(store_PRE_VESSEL3_PLACE_OF_RECEIPT2, "PLACE OF RECEIPT"),
		};
		static private CommandCSV command_PRE_VESSEL3 = new CommandCSV("PRE.VESSEL", columns_PRE_VESSEL3, false, "\'\r\n", ":", '\0', '\0', true);

		// CSV PORTS2
		static private CommandStore store_PORTS2_RECORD_ID21 = new CommandStore("RECORD ID", 0, "");
		static private CommandStore store_PORTS2_LOAD_PORT_CODE2 = new CommandStore("LOAD PORT CODE", 0, "");
		static private CommandStore store_PORTS2_LOAD_PORT2 = new CommandStore("LOAD PORT", 0, "");
		static private CommandStore store_PORTS2_DISCHARGE_PORT_CODE2 = new CommandStore("DISCHARGE PORT CODE", 0, "");
		static private CommandStore store_PORTS2_DISCHARGE_PORT2 = new CommandStore("DISCHARGE PORT", 0, "");
		static private CommandStore store_PORTS2_DELIVERY_PORT2 = new CommandStore("DELIVERY PORT", 0, "");
		static private CommandStore store_PORTS2_PLACE_OF_DELIVERY2 = new CommandStore("PLACE OF DELIVERY", 0, "");
		static private CommandStore store_PORTS2_FINAL_DESTINATION_CODE2 = new CommandStore("FINAL DESTINATION CODE", 0, "");
		static private CommandStore store_PORTS2_FINAL_DESTINATION2 = new CommandStore("FINAL DESTINATION", 0, "");
		static private CommandStore store_PORTS2_POL_DESCRIPTION2 = new CommandStore("POL DESCRIPTION", 0, "");
		static private CommandStore store_PORTS2_POD_DESCRIPTION2 = new CommandStore("POD DESCRIPTION", 0, "");
		static private CommandStore store_PORTS2_DEL_DESCRIPTION2 = new CommandStore("DEL DESCRIPTION", 0, "");
		static private ColumnDelimited[] columns_PORTS2 = {
			new ColumnDelimited(store_PORTS2_RECORD_ID21, "RECORD ID"),
			new ColumnDelimited(store_PORTS2_LOAD_PORT_CODE2, "LOAD PORT CODE"),
			new ColumnDelimited(store_PORTS2_LOAD_PORT2, "LOAD PORT"),
			new ColumnDelimited(store_PORTS2_DISCHARGE_PORT_CODE2, "DISCHARGE PORT CODE"),
			new ColumnDelimited(store_PORTS2_DISCHARGE_PORT2, "DISCHARGE PORT"),
			new ColumnDelimited(store_PORTS2_DELIVERY_PORT2, "DELIVERY PORT"),
			new ColumnDelimited(store_PORTS2_PLACE_OF_DELIVERY2, "PLACE OF DELIVERY"),
			new ColumnDelimited(store_PORTS2_FINAL_DESTINATION_CODE2, "FINAL DESTINATION CODE"),
			new ColumnDelimited(store_PORTS2_FINAL_DESTINATION2, "FINAL DESTINATION"),
			new ColumnDelimited(store_PORTS2_POL_DESCRIPTION2, "POL DESCRIPTION"),
			new ColumnDelimited(store_PORTS2_POD_DESCRIPTION2, "POD DESCRIPTION"),
			new ColumnDelimited(store_PORTS2_DEL_DESCRIPTION2, "DEL DESCRIPTION"),
		};
		static private CommandCSV command_PORTS2 = new CommandCSV("PORTS", columns_PORTS2, false, "\'\r\n", ":", '\0', '\0', true);

		// CSV BOOKING_NO2
		static private CommandStore store_BOOKING_NO2_RECORD_ID25 = new CommandStore("RECORD ID", 0, "");
		static private CommandStore store_BOOKING_NO2_ISSUE_PARTY_CODE2 = new CommandStore("ISSUE PARTY CODE", 0, "");
		static private CommandStore store_BOOKING_NO2_SLOT_CHARTER_ID2 = new CommandStore("SLOT CHARTER ID", 0, "");
		static private CommandStore store_BOOKING_NO2_BOOKING_NO_ID2 = new CommandStore("BOOKING NO.ID", 0, "");
		static private CommandStore store_BOOKING_NO2_BOOKING_NO_2 = new CommandStore("BOOKING NO.", 0, "");
		static private CommandStore store_BOOKING_NO2_APPLICANT2 = new CommandStore("APPLICANT", 0, "");
		static private CommandStore store_BOOKING_NO2_BOKKING_PARTY2 = new CommandStore("BOKKING PARTY", 0, "");
		static private CommandStore store_BOOKING_NO2_FOB_BK_PARTY2 = new CommandStore("FOB BK PARTY", 0, "");
		static private CommandStore store_BOOKING_NO2_DELIVERY_TERM2 = new CommandStore("DELIVERY TERM", 0, "");
		static private CommandStore store_BOOKING_NO2_PREPAID_OR_COLLECT2 = new CommandStore("PREPAID OR COLLECT", 0, "");
		static private CommandStore store_BOOKING_NO2_QUOTATION_NO_2 = new CommandStore("QUOTATION NO.", 0, "");
		static private CommandStore store_BOOKING_NO2_S_C_NO_2 = new CommandStore("S/C NO.", 0, "");
		static private CommandStore store_BOOKING_NO2_QUARANTINE_CODING2 = new CommandStore("QUARANTINE CODING", 0, "");
		static private CommandStore store_BOOKING_NO2_CHARGE_TYPE2 = new CommandStore("CHARGE TYPE", 0, "");
		static private CommandStore store_BOOKING_NO2_SCAC_CODE2 = new CommandStore("SCAC CODE", 0, "");
		static private CommandStore store_BOOKING_NO2_H_B_L2 = new CommandStore("H B/L", 0, "");
		static private ColumnDelimited[] columns_BOOKING_NO2 = {
			new ColumnDelimited(store_BOOKING_NO2_RECORD_ID25, "RECORD ID"),
			new ColumnDelimited(store_BOOKING_NO2_ISSUE_PARTY_CODE2, "ISSUE PARTY CODE"),
			new ColumnDelimited(store_BOOKING_NO2_SLOT_CHARTER_ID2, "SLOT CHARTER ID"),
			new ColumnDelimited(store_BOOKING_NO2_BOOKING_NO_ID2, "BOOKING NO.ID"),
			new ColumnDelimited(store_BOOKING_NO2_BOOKING_NO_2, "BOOKING NO."),
			new ColumnDelimited(store_BOOKING_NO2_APPLICANT2, "APPLICANT"),
			new ColumnDelimited(store_BOOKING_NO2_BOKKING_PARTY2, "BOKKING PARTY"),
			new ColumnDelimited(store_BOOKING_NO2_FOB_BK_PARTY2, "FOB BK PARTY"),
			new ColumnDelimited(store_BOOKING_NO2_DELIVERY_TERM2, "DELIVERY TERM"),
			new ColumnDelimited(store_BOOKING_NO2_PREPAID_OR_COLLECT2, "PREPAID OR COLLECT"),
			new ColumnDelimited(store_BOOKING_NO2_QUOTATION_NO_2, "QUOTATION NO."),
			new ColumnDelimited(store_BOOKING_NO2_S_C_NO_2, "S/C NO."),
			new ColumnDelimited(store_BOOKING_NO2_QUARANTINE_CODING2, "QUARANTINE CODING"),
			new ColumnDelimited(store_BOOKING_NO2_CHARGE_TYPE2, "CHARGE TYPE"),
			new ColumnDelimited(store_BOOKING_NO2_SCAC_CODE2, "SCAC CODE"),
			new ColumnDelimited(store_BOOKING_NO2_H_B_L2, "H B/L"),
		};
		static private CommandCSV command_BOOKING_NO2 = new CommandCSV("BOOKING NO", columns_BOOKING_NO2, false, "\'\r\n", ":", '\0', '\0', true);

		// CSV SHIPPER3
		static private CommandStore store_SHIPPER3_RECORD_ID26 = new CommandStore("RECORD ID", 0, "");
		static private CommandStore store_SHIPPER3_SHIPPER_CODE3 = new CommandStore("SHIPPER CODE", 0, "");
		static private CommandStore store_SHIPPER3_SHIPPER4 = new CommandStore("SHIPPER", 0, "");
		static private CommandStore store_SHIPPER3_RECORD_ID27 = new CommandStore("RECORD ID2", 0, "");
		static private CommandStore store_SHIPPER3_SHIPPER_CODE22 = new CommandStore("SHIPPER CODE2", 0, "");
		static private CommandStore store_SHIPPER3_SHIPPER23 = new CommandStore("SHIPPER2", 0, "");
		static private ColumnDelimited[] columns_SHIPPER3 = {
			new ColumnDelimited(store_SHIPPER3_RECORD_ID26, "RECORD ID"),
			new ColumnDelimited(store_SHIPPER3_SHIPPER_CODE3, "SHIPPER CODE"),
			new ColumnDelimited(store_SHIPPER3_SHIPPER4, "SHIPPER"),
			new ColumnDelimited(store_SHIPPER3_RECORD_ID27, "RECORD ID2"),
			new ColumnDelimited(store_SHIPPER3_SHIPPER_CODE22, "SHIPPER CODE2"),
			new ColumnDelimited(store_SHIPPER3_SHIPPER23, "SHIPPER2"),
		};
		static private CommandCSV command_SHIPPER3 = new CommandCSV("SHIPPER", columns_SHIPPER3, false, "\'\r\n", ":", '\0', '\0', true);

		// CSV CONSIGNE2
		static private CommandStore store_CONSIGNE2_RECORD_ID28 = new CommandStore("RECORD ID", 0, "");
		static private CommandStore store_CONSIGNE2_CONSIGNEE_CODE3 = new CommandStore("CONSIGNEE CODE", 0, "");
		static private CommandStore store_CONSIGNE2_CONSIGNEE3 = new CommandStore("CONSIGNEE", 0, "");
		static private CommandStore store_CONSIGNE2_RECORD_ID29 = new CommandStore("RECORD ID2", 0, "");
		static private CommandStore store_CONSIGNE2_CONSIGNEE_CODE22 = new CommandStore("CONSIGNEE CODE2", 0, "");
		static private CommandStore store_CONSIGNE2_CONSIGNEE22 = new CommandStore("CONSIGNEE2", 0, "");
		static private ColumnDelimited[] columns_CONSIGNE2 = {
			new ColumnDelimited(store_CONSIGNE2_RECORD_ID28, "RECORD ID"),
			new ColumnDelimited(store_CONSIGNE2_CONSIGNEE_CODE3, "CONSIGNEE CODE"),
			new ColumnDelimited(store_CONSIGNE2_CONSIGNEE3, "CONSIGNEE"),
			new ColumnDelimited(store_CONSIGNE2_RECORD_ID29, "RECORD ID2"),
			new ColumnDelimited(store_CONSIGNE2_CONSIGNEE_CODE22, "CONSIGNEE CODE2"),
			new ColumnDelimited(store_CONSIGNE2_CONSIGNEE22, "CONSIGNEE2"),
		};
		static private CommandCSV command_CONSIGNE2 = new CommandCSV("CONSIGNE", columns_CONSIGNE2, false, "\'\r\n", ":", '\0', '\0', true);

		// CSV NOTIFY_PARTY2
		static private CommandStore store_NOTIFY_PARTY2_RECORD_ID30 = new CommandStore("RECORD ID", 0, "");
		static private CommandStore store_NOTIFY_PARTY2_NOTIFY_CODE3 = new CommandStore("NOTIFY CODE", 0, "");
		static private CommandStore store_NOTIFY_PARTY2_NOTIFY3 = new CommandStore("NOTIFY", 0, "");
		static private CommandStore store_NOTIFY_PARTY2_RECORD_ID210 = new CommandStore("RECORD ID2", 0, "");
		static private CommandStore store_NOTIFY_PARTY2_NOTIFY_CODE22 = new CommandStore("NOTIFY CODE2", 0, "");
		static private CommandStore store_NOTIFY_PARTY2_NOTIFY22 = new CommandStore("NOTIFY2", 0, "");
		static private ColumnDelimited[] columns_NOTIFY_PARTY2 = {
			new ColumnDelimited(store_NOTIFY_PARTY2_RECORD_ID30, "RECORD ID"),
			new ColumnDelimited(store_NOTIFY_PARTY2_NOTIFY_CODE3, "NOTIFY CODE"),
			new ColumnDelimited(store_NOTIFY_PARTY2_NOTIFY3, "NOTIFY"),
			new ColumnDelimited(store_NOTIFY_PARTY2_RECORD_ID210, "RECORD ID2"),
			new ColumnDelimited(store_NOTIFY_PARTY2_NOTIFY_CODE22, "NOTIFY CODE2"),
			new ColumnDelimited(store_NOTIFY_PARTY2_NOTIFY22, "NOTIFY2"),
		};
		static private CommandCSV command_NOTIFY_PARTY2 = new CommandCSV("NOTIFY PARTY", columns_NOTIFY_PARTY2, false, "\'\r\n", ":", '\0', '\0', true);

		// CSV CONTAINER_OF_BOOKING2
		static private CommandStore store_CONTAINER_OF_BOOKING2_RECORD_ID31 = new CommandStore("RECORD ID", 0, "");
		static private CommandStore store_CONTAINER_OF_BOOKING2_CTN_SIZE_TYPE2 = new CommandStore("CTN.SIZE&TYPE", 0, "");
		static private CommandStore store_CONTAINER_OF_BOOKING2_CTN_NUMBERS2 = new CommandStore("CTN.NUMBERS", 0, "");
		static private CommandStore store_CONTAINER_OF_BOOKING2_CTN_STATUS2 = new CommandStore("CTN.STATUS", 0, "");
		static private CommandStore store_CONTAINER_OF_BOOKING2_CTN_NO_12 = new CommandStore("CTN.NO.1", 0, "");
		static private CommandStore store_CONTAINER_OF_BOOKING2_VANNING_DEPOT2 = new CommandStore("VANNING DEPOT", 0, "");
		static private CommandStore store_CONTAINER_OF_BOOKING2_COUNTAINER_SOC_2 = new CommandStore("COUNTAINER SOC.", 0, "");
		static private ColumnDelimited[] columns_CONTAINER_OF_BOOKING2 = {
			new ColumnDelimited(store_CONTAINER_OF_BOOKING2_RECORD_ID31, "RECORD ID"),
			new ColumnDelimited(store_CONTAINER_OF_BOOKING2_CTN_SIZE_TYPE2, "CTN.SIZE&TYPE"),
			new ColumnDelimited(store_CONTAINER_OF_BOOKING2_CTN_NUMBERS2, "CTN.NUMBERS"),
			new ColumnDelimited(store_CONTAINER_OF_BOOKING2_CTN_STATUS2, "CTN.STATUS"),
			new ColumnDelimited(store_CONTAINER_OF_BOOKING2_CTN_NO_12, "CTN.NO.1"),
			new ColumnDelimited(store_CONTAINER_OF_BOOKING2_VANNING_DEPOT2, "VANNING DEPOT"),
			new ColumnDelimited(store_CONTAINER_OF_BOOKING2_COUNTAINER_SOC_2, "COUNTAINER SOC."),
		};
		static private CommandCSV command_CONTAINER_OF_BOOKING2 = new CommandCSV("CONTAINER OF BOOKING", columns_CONTAINER_OF_BOOKING2, false, "\'\r\n", ":", '\0', '\0', true);

		// CSV CARGO_OF_BOOKING2
		static private CommandStore store_CARGO_OF_BOOKING2_RECORD_ID32 = new CommandStore("RECORD-ID", 0, "");
		static private CommandStore store_CARGO_OF_BOOKING2_CARGO_SEQUENCE2 = new CommandStore("CARGO SEQUENCE", 0, "");
		static private CommandStore store_CARGO_OF_BOOKING2_CARGO_CODE2 = new CommandStore("CARGO CODE", 0, "");
		static private CommandStore store_CARGO_OF_BOOKING2_CARGO_ID2 = new CommandStore("CARGO ID", 0, "");
		static private CommandStore store_CARGO_OF_BOOKING2_NUMBERS_OF_PKGS_12 = new CommandStore("NUMBERS OF PKGS-1", 0, "");
		static private CommandStore store_CARGO_OF_BOOKING2_CODE_OF_PKGS_12 = new CommandStore("CODE OF PKGS-1", 0, "");
		static private CommandStore store_CARGO_OF_BOOKING2_PACKAGES_DES_12 = new CommandStore("PACKAGES DES-1", 0, "");
		static private CommandStore store_CARGO_OF_BOOKING2_CARGO_GROSS_WT_12 = new CommandStore("CARGO GROSS WT-1", 0, "");
		static private CommandStore store_CARGO_OF_BOOKING2_CARGO_MEASUREMENT_12 = new CommandStore("CARGO MEASUREMENT-1", 0, "");
		static private CommandStore store_CARGO_OF_BOOKING2_NUMBERS_OF_PACKAGES_22 = new CommandStore("NUMBERS OF PACKAGES-2", 0, "");
		static private CommandStore store_CARGO_OF_BOOKING2_CODE_OF_PKGS_22 = new CommandStore("CODE OF PKGS-2", 0, "");
		static private CommandStore store_CARGO_OF_BOOKING2_PACKAGES_DES_22 = new CommandStore("PACKAGES DES-2", 0, "");
		static private CommandStore store_CARGO_OF_BOOKING2_CARGO_GROSS_WT_22 = new CommandStore("CARGO GROSS WT-2", 0, "");
		static private CommandStore store_CARGO_OF_BOOKING2_CARGO_MEASUREMENT_22 = new CommandStore("CARGO MEASUREMENT-2", 0, "");
		static private CommandStore store_CARGO_OF_BOOKING2_CARGO_NET_WEIGHT2 = new CommandStore("CARGO NET WEIGHT", 0, "");
		static private ColumnDelimited[] columns_CARGO_OF_BOOKING2 = {
			new ColumnDelimited(store_CARGO_OF_BOOKING2_RECORD_ID32, "RECORD-ID"),
			new ColumnDelimited(store_CARGO_OF_BOOKING2_CARGO_SEQUENCE2, "CARGO SEQUENCE"),
			new ColumnDelimited(store_CARGO_OF_BOOKING2_CARGO_CODE2, "CARGO CODE"),
			new ColumnDelimited(store_CARGO_OF_BOOKING2_CARGO_ID2, "CARGO ID"),
			new ColumnDelimited(store_CARGO_OF_BOOKING2_NUMBERS_OF_PKGS_12, "NUMBERS OF PKGS-1"),
			new ColumnDelimited(store_CARGO_OF_BOOKING2_CODE_OF_PKGS_12, "CODE OF PKGS-1"),
			new ColumnDelimited(store_CARGO_OF_BOOKING2_PACKAGES_DES_12, "PACKAGES DES-1"),
			new ColumnDelimited(store_CARGO_OF_BOOKING2_CARGO_GROSS_WT_12, "CARGO GROSS WT-1"),
			new ColumnDelimited(store_CARGO_OF_BOOKING2_CARGO_MEASUREMENT_12, "CARGO MEASUREMENT-1"),
			new ColumnDelimited(store_CARGO_OF_BOOKING2_NUMBERS_OF_PACKAGES_22, "NUMBERS OF PACKAGES-2"),
			new ColumnDelimited(store_CARGO_OF_BOOKING2_CODE_OF_PKGS_22, "CODE OF PKGS-2"),
			new ColumnDelimited(store_CARGO_OF_BOOKING2_PACKAGES_DES_22, "PACKAGES DES-2"),
			new ColumnDelimited(store_CARGO_OF_BOOKING2_CARGO_GROSS_WT_22, "CARGO GROSS WT-2"),
			new ColumnDelimited(store_CARGO_OF_BOOKING2_CARGO_MEASUREMENT_22, "CARGO MEASUREMENT-2"),
			new ColumnDelimited(store_CARGO_OF_BOOKING2_CARGO_NET_WEIGHT2, "CARGO NET WEIGHT"),
		};
		static private CommandCSV command_CARGO_OF_BOOKING2 = new CommandCSV("CARGO OF BOOKING", columns_CARGO_OF_BOOKING2, false, "\'\r\n", ":", '\0', '\0', true);

		// CSV DANGEROUS_REEFER_OOG2
		static private CommandStore store_DANGEROUS_REEFER_OOG2_RECORDE_ID2 = new CommandStore("RECORDE ID", 0, "");
		static private CommandStore store_DANGEROUS_REEFER_OOG2_DANGEROUS2 = new CommandStore("DANGEROUS", 0, "");
		static private CommandStore store_DANGEROUS_REEFER_OOG2_CLASS3 = new CommandStore("CLASS", 0, "");
		static private CommandStore store_DANGEROUS_REEFER_OOG2_PAGE2 = new CommandStore("PAGE", 0, "");
		static private CommandStore store_DANGEROUS_REEFER_OOG2_UNDG_NO_2 = new CommandStore("UNDG NO.", 0, "");
		static private CommandStore store_DANGEROUS_REEFER_OOG2_LABEL2 = new CommandStore("LABEL", 0, "");
		static private CommandStore store_DANGEROUS_REEFER_OOG2_FLASH_POINT2 = new CommandStore("FLASH POINT", 0, "");
		static private CommandStore store_DANGEROUS_REEFER_OOG2_REEFER2 = new CommandStore("REEFER", 0, "");
		static private CommandStore store_DANGEROUS_REEFER_OOG2_TEMPERATURE_SETTING2 = new CommandStore("TEMPERATURE SETTING", 0, "");
		static private ColumnDelimited[] columns_DANGEROUS_REEFER_OOG2 = {
			new ColumnDelimited(store_DANGEROUS_REEFER_OOG2_RECORDE_ID2, "RECORDE ID"),
			new ColumnDelimited(store_DANGEROUS_REEFER_OOG2_DANGEROUS2, "DANGEROUS"),
			new ColumnDelimited(store_DANGEROUS_REEFER_OOG2_CLASS3, "CLASS"),
			new ColumnDelimited(store_DANGEROUS_REEFER_OOG2_PAGE2, "PAGE"),
			new ColumnDelimited(store_DANGEROUS_REEFER_OOG2_UNDG_NO_2, "UNDG NO."),
			new ColumnDelimited(store_DANGEROUS_REEFER_OOG2_LABEL2, "LABEL"),
			new ColumnDelimited(store_DANGEROUS_REEFER_OOG2_FLASH_POINT2, "FLASH POINT"),
			new ColumnDelimited(store_DANGEROUS_REEFER_OOG2_REEFER2, "REEFER"),
			new ColumnDelimited(store_DANGEROUS_REEFER_OOG2_TEMPERATURE_SETTING2, "TEMPERATURE SETTING"),
		};
		static private CommandCSV command_DANGEROUS_REEFER_OOG2 = new CommandCSV("DANGEROUS\uFF0CREEFER&OOG", columns_DANGEROUS_REEFER_OOG2, false, "\'\r\n", ":", '\0', '\0', true);

		// CSV MARKS_NOS_2
		static private CommandStore store_MARKS_NOS_2_RECORD_ID33 = new CommandStore("RECORD ID", 0, "");
		static private CommandStore store_MARKS_NOS_2_CARGO_DESCRIPTION_1_5_2 = new CommandStore("CARGO DESCRIPTION(1-5)", 0, "");
		static private ColumnDelimited[] columns_MARKS_NOS_2 = {
			new ColumnDelimited(store_MARKS_NOS_2_RECORD_ID33, "RECORD ID"),
			new ColumnDelimited(store_MARKS_NOS_2_CARGO_DESCRIPTION_1_5_2, "CARGO DESCRIPTION(1-5)"),
		};
		static private CommandCSV command_MARKS_NOS_2 = new CommandCSV("MARKS&NOS.", columns_MARKS_NOS_2, false, "\'\r\n", ":", '\0', '\0', true);

		// CSV CARGO_DESCRIPTION3
		static private CommandStore store_CARGO_DESCRIPTION3_RECORD_ID34 = new CommandStore("RECORD ID", 0, "");
		static private CommandStore store_CARGO_DESCRIPTION3_CARGO_DESCRIPTION4 = new CommandStore("CARGO DESCRIPTION", 0, "");
		static private ColumnDelimited[] columns_CARGO_DESCRIPTION3 = {
			new ColumnDelimited(store_CARGO_DESCRIPTION3_RECORD_ID34, "RECORD ID"),
			new ColumnDelimited(store_CARGO_DESCRIPTION3_CARGO_DESCRIPTION4, "CARGO DESCRIPTION"),
		};
		static private CommandCSV command_CARGO_DESCRIPTION3 = new CommandCSV("CARGO DESCRIPTION", columns_CARGO_DESCRIPTION3, false, "\'\r\n", ":", '\0', '\0', true);

		// CSV FREIGHT_CLAUSE2
		static private CommandStore store_FREIGHT_CLAUSE2_RECORD_ID35 = new CommandStore("RECORD ID", 0, "");
		static private CommandStore store_FREIGHT_CLAUSE2_FR_CLAUSE_CODE2 = new CommandStore("FR.CLAUSE.CODE", 0, "");
		static private CommandStore store_FREIGHT_CLAUSE2_FREIGHT_CLAUSE_I_1_2_2 = new CommandStore("FREIGHT CLAUSE-I\uFF081-2\uFF09", 0, "");
		static private CommandStore store_FREIGHT_CLAUSE2_Freight2 = new CommandStore("Freight", 0, "");
		static private CommandStore store_FREIGHT_CLAUSE2_PayPlace2 = new CommandStore("PayPlace", 0, "");
		static private ColumnDelimited[] columns_FREIGHT_CLAUSE2 = {
			new ColumnDelimited(store_FREIGHT_CLAUSE2_RECORD_ID35, "RECORD ID"),
			new ColumnDelimited(store_FREIGHT_CLAUSE2_FR_CLAUSE_CODE2, "FR.CLAUSE.CODE"),
			new ColumnDelimited(store_FREIGHT_CLAUSE2_FREIGHT_CLAUSE_I_1_2_2, "FREIGHT CLAUSE-I\uFF081-2\uFF09"),
			new ColumnDelimited(store_FREIGHT_CLAUSE2_Freight2, "Freight"),
			new ColumnDelimited(store_FREIGHT_CLAUSE2_PayPlace2, "PayPlace"),
		};
		static private CommandCSV command_FREIGHT_CLAUSE2 = new CommandCSV("FREIGHT CLAUSE", columns_FREIGHT_CLAUSE2, false, "\'\r\n", ":", '\0', '\0', true);

		// CSV REMARKS3
		static private CommandStore store_REMARKS3_RECORD_ID36 = new CommandStore("RECORD ID", 0, "");
		static private CommandStore store_REMARKS3_REMARKS4 = new CommandStore("REMARKS", 0, "");
		static private ColumnDelimited[] columns_REMARKS3 = {
			new ColumnDelimited(store_REMARKS3_RECORD_ID36, "RECORD ID"),
			new ColumnDelimited(store_REMARKS3_REMARKS4, "REMARKS"),
		};
		static private CommandCSV command_REMARKS3 = new CommandCSV("REMARKS", columns_REMARKS3, false, "\'\r\n", ":", '\0', '\0', true);

		// CSV B_L2
		static private CommandStore store_B_L2_RECORD_ID37 = new CommandStore("RECORD ID", 0, "");
		static private CommandStore store_B_L2_TYPE_OF_B_L_FORM2 = new CommandStore("TYPE OF B/L FORM", 0, "");
		static private CommandStore store_B_L2_TYPE_OF_B_L_ISSUE_CODE2 = new CommandStore("TYPE OF B/L ISSUE CODE", 0, "");
		static private CommandStore store_B_L2_DATE_OF_ISSUE2 = new CommandStore("DATE OF ISSUE", 0, "");
		static private CommandStore store_B_L2_NUMBERS_OF_ORIGINAL_B_L2 = new CommandStore("NUMBERS OF ORIGINAL B/L", 0, "");
		static private CommandStore store_B_L2_PREPAID_AT2 = new CommandStore("PREPAID AT", 0, "");
		static private CommandStore store_B_L2_AYABLE_AT2 = new CommandStore("AYABLE AT", 0, "");
		static private ColumnDelimited[] columns_B_L2 = {
			new ColumnDelimited(store_B_L2_RECORD_ID37, "RECORD ID"),
			new ColumnDelimited(store_B_L2_TYPE_OF_B_L_FORM2, "TYPE OF B/L FORM"),
			new ColumnDelimited(store_B_L2_TYPE_OF_B_L_ISSUE_CODE2, "TYPE OF B/L ISSUE CODE"),
			new ColumnDelimited(store_B_L2_DATE_OF_ISSUE2, "DATE OF ISSUE"),
			new ColumnDelimited(store_B_L2_NUMBERS_OF_ORIGINAL_B_L2, "NUMBERS OF ORIGINAL B/L"),
			new ColumnDelimited(store_B_L2_PREPAID_AT2, "PREPAID AT"),
			new ColumnDelimited(store_B_L2_AYABLE_AT2, "AYABLE AT"),
		};
		static private CommandCSV command_B_L2 = new CommandCSV("B/L", columns_B_L2, false, "\'\r\n", ":", '\0', '\0', true);

		// CSV BookingDes2
		static private CommandStore store_BookingDes2_RECORD_ID38 = new CommandStore("RECORD ID", 0, "");
		static private CommandStore store_BookingDes2_SeaDesc2 = new CommandStore("SeaDesc", 0, "");
		static private ColumnDelimited[] columns_BookingDes2 = {
			new ColumnDelimited(store_BookingDes2_RECORD_ID38, "RECORD ID"),
			new ColumnDelimited(store_BookingDes2_SeaDesc2, "SeaDesc"),
		};
		static private CommandCSV command_BookingDes2 = new CommandCSV("BookingDes", columns_BookingDes2, false, "\'\r\n", ":", '\0', '\0', true);

		// CSV TRAILER_RECORD2
		static private CommandStore store_TRAILER_RECORD2_RECORD_ID39 = new CommandStore("RECORD ID", 0, "");
		static private CommandStore store_TRAILER_RECORD2_RECORD_TOTAL_OF_FILE2 = new CommandStore("RECORD TOTAL OF FILE", 0, "");
		static private ColumnDelimited[] columns_TRAILER_RECORD2 = {
			new ColumnDelimited(store_TRAILER_RECORD2_RECORD_ID39, "RECORD ID"),
			new ColumnDelimited(store_TRAILER_RECORD2_RECORD_TOTAL_OF_FILE2, "RECORD TOTAL OF FILE"),
		};
		static private CommandCSV command_TRAILER_RECORD2 = new CommandCSV("TRAILER RECORD", columns_TRAILER_RECORD2, false, "\'\r\n", ":", '\0', '\0', true);

		/// <summary>
		/// Constructor
		/// </summary>
		public CSCLBookingDocument()	
		{
			command_Root2.SetNext(command_Sections2);
			command_Sections2.conditions[0].SetNext(command_HEAD_RECORD2);
			command_Sections2.conditions[1].SetNext(command_VESSEL3);
			command_Sections2.conditions[2].SetNext(command_PRE_VESSEL3);
			command_Sections2.conditions[3].SetNext(command_PORTS2);
			command_Sections2.conditions[4].SetNext(command_BOOKING_NO2);
			command_Sections2.conditions[5].SetNext(command_SHIPPER3);
			command_Sections2.conditions[6].SetNext(command_CONSIGNE2);
			command_Sections2.conditions[7].SetNext(command_NOTIFY_PARTY2);
			command_Sections2.conditions[8].SetNext(command_CONTAINER_OF_BOOKING2);
			command_Sections2.conditions[9].SetNext(command_CARGO_OF_BOOKING2);
			command_Sections2.conditions[10].SetNext(command_DANGEROUS_REEFER_OOG2);
			command_Sections2.conditions[11].SetNext(command_MARKS_NOS_2);
			command_Sections2.conditions[12].SetNext(command_CARGO_DESCRIPTION3);
			command_Sections2.conditions[13].SetNext(command_FREIGHT_CLAUSE2);
			command_Sections2.conditions[14].SetNext(command_REMARKS3);
			command_Sections2.conditions[15].SetNext(command_B_L2);
			command_Sections2.conditions[16].SetNext(command_BookingDes2);
			command_Sections2.conditions[17].SetNext(command_TRAILER_RECORD2);

			rootCommand = command_Root2;
		}
	}

} // namespace CSCLBooking
